// Water Treatment Study Site — Question Dataset
// Auto-generated by convert.js — do not edit manually
// Source: dsa1.csv
// Generated: 2026-04-30T18:24:50.127Z
// Questions: 161

const questions = [
  {
    "id": "dsa1_true_false_1",
    "source": "dsa1",
    "type": "true_false",
    "number": 1,
    "question": "Many sources of water are directly suitable for drinking purposes without treatment.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Many sources of water are not suitable for drinking without treatment"
  },
  {
    "id": "dsa1_true_false_2",
    "source": "dsa1",
    "type": "true_false",
    "number": 2,
    "question": "Precipitation has a significant amount of microbial content.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "precipitation has virtually no microbial content"
  },
  {
    "id": "dsa1_true_false_3",
    "source": "dsa1",
    "type": "true_false",
    "number": 3,
    "question": "Many organisms that cause disease in humans originate with the fecal discharges of infected humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_4",
    "source": "dsa1",
    "type": "true_false",
    "number": 4,
    "question": "Algal blooms rarely take place in the upper layer of water in the reservoir.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "In most cases algal blooms take place in the upper layer of water"
  },
  {
    "id": "dsa1_true_false_5",
    "source": "dsa1",
    "type": "true_false",
    "number": 5,
    "question": "When measuring turbidity, many small particles will reflect less light than an equivalent large particle.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Many small particles reflect more light than an equivalent large particle"
  },
  {
    "id": "dsa1_true_false_6",
    "source": "dsa1",
    "type": "true_false",
    "number": 6,
    "question": "Operators should allow as much time as possible for the coagulation reaction.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Operator should allow as short a time as possible for coagulation reaction. Rapid mixing!"
  },
  {
    "id": "dsa1_true_false_7",
    "source": "dsa1",
    "type": "true_false",
    "number": 7,
    "question": "A \"popcorn flake\" is a desirable flock appearance.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_8",
    "source": "dsa1",
    "type": "true_false",
    "number": 8,
    "question": "Polymer powders on floors become extremely slippery when wet.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_9",
    "source": "dsa1",
    "type": "true_false",
    "number": 9,
    "question": "Solids-contact process units combine the coagulation, flocculation, and sedimentation processes in a large basin, also called a clarifier.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_10",
    "source": "dsa1",
    "type": "true_false",
    "number": 10,
    "question": "Sludge produced by a solids-contact clarification unit is recycled through the process to act as a coagulant aid, recycling the slude (with chemicals) is also very efficient.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_11",
    "source": "dsa1",
    "type": "true_false",
    "number": 11,
    "question": "Low-turbidity source waters require sedimentation processes.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Low turbidity source waters do not require sedimentation processes"
  },
  {
    "id": "dsa1_true_false_12",
    "source": "dsa1",
    "type": "true_false",
    "number": 12,
    "question": "Processed water samples must be representative of the actual conditions in the treatment plant.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_13",
    "source": "dsa1",
    "type": "true_false",
    "number": 13,
    "question": "Poor chemical treatment can often result in either early turbidity breakthrough or rapid head loss buildup.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_14",
    "source": "dsa1",
    "type": "true_false",
    "number": 14,
    "question": "Backwashing at too high a rate is much more destructive than at too low a back wash rate.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_15",
    "source": "dsa1",
    "type": "true_false",
    "number": 15,
    "question": "Particle counters can be used to indicate the probable removal of Cryptosporidium and Giardia achieved through optimized plant performance for particle removal.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_16",
    "source": "dsa1",
    "type": "true_false",
    "number": 16,
    "question": "Organics found in the water can consume great amounts of chlorine disinfectants while forming unwanted compounds.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_17",
    "source": "dsa1",
    "type": "true_false",
    "number": 17,
    "question": "A chlorine residual in the form of free available residual chlorine has the highest disinfection ability.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_18",
    "source": "dsa1",
    "type": "true_false",
    "number": 18,
    "question": "Use regular pipe fittings when making connections with chlorine containers.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Do not use regular pipe fittings when making connections with containers"
  },
  {
    "id": "dsa1_true_false_19",
    "source": "dsa1",
    "type": "true_false",
    "number": 19,
    "question": "Always add acid to water never the reverse. Think treatment chemicals to a large pool.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_20",
    "source": "dsa1",
    "type": "true_false",
    "number": 20,
    "question": "For corrosion to occur both electric current and chemical reaction must be present.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_21",
    "source": "dsa1",
    "type": "true_false",
    "number": 21,
    "question": "When iron and copper are joined the iron will be protected and the copper will corrode.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "When copper and iron are joined, iron will corrode and copper is protected"
  },
  {
    "id": "dsa1_true_false_22",
    "source": "dsa1",
    "type": "true_false",
    "number": 22,
    "question": "Water containing high levels of hardness tend to be more aggressive.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Water containing very little hardness tends to be more aggressive"
  },
  {
    "id": "dsa1_true_false_23",
    "source": "dsa1",
    "type": "true_false",
    "number": 23,
    "question": "Increase nutrient levels in source water may result from either natural conditions or from human activity within the watershed.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_24",
    "source": "dsa1",
    "type": "true_false",
    "number": 24,
    "question": "Cross connections in the distribution system are potentially very hazardous and a source of taste and odor complaints.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_25",
    "source": "dsa1",
    "type": "true_false",
    "number": 25,
    "question": "Super chlorination is followed by dechlorination as part of the treatment for tastes and odors.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_26",
    "source": "dsa1",
    "type": "true_false",
    "number": 26,
    "question": "Ideally process control measurements should be made on a continuous basis by special instrumentation.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_27",
    "source": "dsa1",
    "type": "true_false",
    "number": 27,
    "question": "A material safety data sheet (MSDS) is your best source of information about dangerous chemicals.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_28",
    "source": "dsa1",
    "type": "true_false",
    "number": 28,
    "question": "Federal laws include sludge from a water treatment plant as an industrial waste and require proper handling and disposal.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_29",
    "source": "dsa1",
    "type": "true_false",
    "number": 29,
    "question": "The collection of a bad sample or a bad laboratory result is about as useful as no results.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_30",
    "source": "dsa1",
    "type": "true_false",
    "number": 30,
    "question": "Completely empty volumetric pipettes by blowing out the small amount remaining in the tip.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Under no circumstance should the small amount remaining in the tip be blown out"
  },
  {
    "id": "dsa1_true_false_31",
    "source": "dsa1",
    "type": "true_false",
    "number": 31,
    "question": "Never pipette chemical reagent solutions or unknown water samples by mouth.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_1",
    "source": "dsa1",
    "type": "best_answer",
    "number": 1,
    "question": "What is the responsibility of water treatment plant operators?",
    "answer": 3,
    "options": [
      "Avoid boil-water orders",
      "Minimize costs of producing drinking water",
      "Produce safe and pleasant drinking water",
      "Successfully pass operator certificate examinations"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_2",
    "source": "dsa1",
    "type": "best_answer",
    "number": 2,
    "question": "What is the cause of stratification in lakes and reservoirs?",
    "answer": 2,
    "options": [
      "Breezes starting the circulation of surface water",
      "Formation of separate layers of temperature, plant life, or animal life",
      "Lake turn over",
      "Uniform water temperature profile in a lake or reservoir"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_3",
    "source": "dsa1",
    "type": "best_answer",
    "number": 3,
    "question": "How extensive should the treatment be for reclaimed water?",
    "answer": 2,
    "options": [
      "All reclaimed water should receive the same degree of treatment",
      "Depends on potential exposure to the public",
      "Depends on the funds available for treatment",
      "Local regulations determine the degree of treatment"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_4",
    "source": "dsa1",
    "type": "best_answer",
    "number": 4,
    "question": "How can iron, manganese, and hydrogen sulfide problems be controlled in a reservoir?",
    "answer": 3,
    "options": [
      "By controlling algal productivity",
      "By improving the fishery habitat",
      "By preventing dissolved oxygen depletion",
      "By regulating recreational activities"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_5",
    "source": "dsa1",
    "type": "best_answer",
    "number": 5,
    "question": "What is the best tool for managing watersheds?",
    "answer": 3,
    "options": [
      "Political process",
      "Public hearings",
      "Regulatory process",
      "Voluntary compliance"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_6",
    "source": "dsa1",
    "type": "best_answer",
    "number": 6,
    "question": "What is the destratification of a lake or reservoir?",
    "answer": 3,
    "options": [
      "Elimination of separate layers by algal blooms",
      "Natural turnover during seasonal changes",
      "Vertical mixing to eliminate separate layers of temperature, plant life, or animal life",
      "Wind blowing across the water surface and causing mixing"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_7",
    "source": "dsa1",
    "type": "best_answer",
    "number": 7,
    "question": "What is the purpose of coagulation and flocculation?",
    "answer": 4,
    "options": [
      "To control corrosion",
      "To kill disease causing organisms",
      "To remove leaves, sticks, fish, and other debris",
      "To remove particle impurities, especially non settle-able solids and colour"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_8",
    "source": "dsa1",
    "type": "best_answer",
    "number": 8,
    "question": "After a jar test is completed, what does a hazy settled water indicate?",
    "answer": 1,
    "options": [
      "Poor coagulation",
      "Poor flocculation",
      "Poor mixing",
      "Poor turbidity"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_9",
    "source": "dsa1",
    "type": "best_answer",
    "number": 9,
    "question": "How can an operator verify the effectiveness of the coagulant chemicals and dosages being applied at the flashmixer?",
    "answer": 4,
    "options": [
      "Determined finished water chlorine demand",
      "Measure raw and finished water temperatures",
      "Measure source water turbidity levels",
      "Perform a series of jar tests"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_10",
    "source": "dsa1",
    "type": "best_answer",
    "number": 10,
    "question": "What happens to the settling rate (settling velocity) of particles in water when the water temperature drops?",
    "answer": 1,
    "options": [
      "Decreases.",
      "Depends on the weather",
      "Increases",
      "Stays constant"
    ],
    "tags": [],
    "context": "Cold equals high viscosity (syrup)"
  },
  {
    "id": "dsa1_best_answer_11",
    "source": "dsa1",
    "type": "best_answer",
    "number": 11,
    "question": "What is the major means by which operators can control water treatment processes?",
    "answer": 1,
    "options": [
      "Adjusting chemicals and at chemical feed rates",
      "Controlling the sedimentation process",
      "Controlling water temperatures",
      "Modifying demands for water"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_12",
    "source": "dsa1",
    "type": "best_answer",
    "number": 12,
    "question": "Which task should be performed immediately following dewatering of a sedimentation basin?",
    "answer": 1,
    "options": [
      "Grease and lubricate all gears, sprockets, and mechanical moving parts that have been submerged",
      "Perform necessary laboratory analysis",
      "Record all gauge and meter readings",
      "Stop flow to the sedimentation basin"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_13",
    "source": "dsa1",
    "type": "best_answer",
    "number": 13,
    "question": "How are filter production (capacity) rates measured?",
    "answer": 3,
    "options": [
      "GPM",
      "GPM/ sq. ft.",
      "MGD",
      "MGD/ sq. ft."
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_14",
    "source": "dsa1",
    "type": "best_answer",
    "number": 14,
    "question": "Why is surface wash used during backwashing?",
    "answer": 1,
    "options": [
      "To prevent mud balls",
      "To provide a backup for backwash systems",
      "To reduce backwash water requirements",
      "To wash walls of the filter"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_15",
    "source": "dsa1",
    "type": "best_answer",
    "number": 15,
    "question": "What do significant changes in source water turbidity levels, either increases or decreases, require?",
    "answer": 2,
    "options": [
      "Adjustment of filter runtime to accommodate change",
      "Immediate verification of filtration process effectiveness",
      "Observation of head loss to reveal the need for process adjustment",
      "Performance of jar tests to determine optimum chemical dose"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_16",
    "source": "dsa1",
    "type": "best_answer",
    "number": 16,
    "question": "Why should a filter be drained if it is going to be out of service for a prolonged.?",
    "answer": 2,
    "options": [
      "To allow the media to dry out",
      "To avoid algal growth",
      "To prevent filter tank from floating on groundwater",
      "To save water"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_17",
    "source": "dsa1",
    "type": "best_answer",
    "number": 17,
    "question": "Why has there been an increased interest in disinfectants other than chlorine?",
    "answer": 1,
    "options": [
      "Chlorine may form carcinogenic compounds, THMs (trihalomethanes)",
      "Other disinfectants are cheaper",
      "Other disinfectants are more readily available",
      "Other disinfectants leave a better disinfecting residual"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_18",
    "source": "dsa1",
    "type": "best_answer",
    "number": 18,
    "question": "What are the components of a chlorine residual?",
    "answer": 2,
    "options": [
      "Chlorine demand plus chlorine dose",
      "Combine chlorine forms plus free chlorine",
      "Free chlorine plus chlorine dose",
      "Hypochlorous acid plus hypochloric acid"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_19",
    "source": "dsa1",
    "type": "best_answer",
    "number": 19,
    "question": "Where should the minimum chlorine residual be measured in the distribution system?",
    "answer": 2,
    "options": [
      "At the beginning of the distribution system",
      "At the most remote location in the system",
      "In the distribution system service storage tank",
      "Just downstream from where the disinfectant is being fed into the system"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_20",
    "source": "dsa1",
    "type": "best_answer",
    "number": 20,
    "question": "How are ORP probes used in the disinfection process?",
    "answer": 3,
    "options": [
      "They accurately measure chlorine dosage",
      "They measure the liquid chlorine remaining in a chlorine container",
      "They provide a direct measure of the disinfecting power of the disinfectant",
      "They quickly measure and record chlorine residuals"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_21",
    "source": "dsa1",
    "type": "best_answer",
    "number": 21,
    "question": "Why are zinc and magnesium commonly used as sacrificial anodes in water tanks or for varied pipes?",
    "answer": 1,
    "options": [
      "They will corrode preferentially to aluminum and iron",
      "They will form a protective coating over the other metals",
      "They will last longer than other metals in corrosive waters",
      "They will not corrode when electrons flow in a tank or pipe"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_22",
    "source": "dsa1",
    "type": "best_answer",
    "number": 22,
    "question": "Why should samples for corrosivity tests be taken only after post chlorination?",
    "answer": 1,
    "options": [
      "Because disinfectant chemicals may react with corrosion-control chemicals to either increase or decrease corrosivity",
      "Because samples should be collected in areas where corrosion is likely to occur",
      "To allow time for mixing of all chemicals",
      "To ensure collection of representative samples"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_23",
    "source": "dsa1",
    "type": "best_answer",
    "number": 23,
    "question": "Where are the monitoring samples for the Lead and Copper Rule collected?",
    "answer": 1,
    "options": [
      "At the consumers tab",
      "At the entrance to the clairwell",
      "At the most distant locations in the distribution system",
      "At the raw water source"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_24",
    "source": "dsa1",
    "type": "best_answer",
    "number": 24,
    "question": "What is the secret to successful taste and odor control?",
    "answer": 2,
    "options": [
      "Implement an effective public relations program",
      "Prevent taste and odors from ever developing",
      "Provide consumers with treatment option information",
      "Treat taste and odors when the first complaint is received"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_25",
    "source": "dsa1",
    "type": "best_answer",
    "number": 25,
    "question": "Taste and odor treatment methods can be divided into which categories?",
    "answer": 4,
    "options": [
      "Coagulation/ flocculation",
      "Degassification/ adsorption",
      "Oxidation/ reduction",
      "Removal/ destruction"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_26",
    "source": "dsa1",
    "type": "best_answer",
    "number": 26,
    "question": "Where is powdered activated carbon often applied?",
    "answer": 3,
    "options": [
      "After chlorination",
      "After filtration",
      "At flashmixer",
      "At floc tanks"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_27",
    "source": "dsa1",
    "type": "best_answer",
    "number": 27,
    "question": "Over which water quality indicator do operators have the greatest control?",
    "answer": 4,
    "options": [
      "Alkalinity",
      "pH",
      "Temperature",
      "Turbidity"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_28",
    "source": "dsa1",
    "type": "best_answer",
    "number": 28,
    "question": "Which chemical is one of the most dangerous of the common alkalies?",
    "answer": 2,
    "options": [
      "Calcium hydroxide",
      "Caustic soda",
      "Chlorine",
      "Sodium bicarbonate"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_29",
    "source": "dsa1",
    "type": "best_answer",
    "number": 29,
    "question": "What should an operator do first when a treatment process upset results in the failure to meet a specific drinking water quality standard?",
    "answer": 2,
    "options": [
      "Fix process upset",
      "Notify appropriate local health authorities",
      "Stop operating process",
      "Switch sources of raw water"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_30",
    "source": "dsa1",
    "type": "best_answer",
    "number": 30,
    "question": "Which piece of laboratory equipment is the most accurate way to measure a volume of liquid?",
    "answer": 4,
    "options": [
      "Beaker",
      "Flask",
      "Graduated cylinder",
      "Pipette"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_31",
    "source": "dsa1",
    "type": "best_answer",
    "number": 31,
    "question": "Which piece of laboratory equipment is used to titrate a chemical reagent?",
    "answer": 2,
    "options": [
      "Buchner funnel",
      "Buret",
      "Graduated cylinder",
      "Pipette"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_32",
    "source": "dsa1",
    "type": "best_answer",
    "number": 32,
    "question": "Which style of thermometer will change most rapidly when removed from the liquid sample?",
    "answer": 4,
    "options": [
      "Dial",
      "Digital",
      "Partial immersion",
      "Total immersion"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_33",
    "source": "dsa1",
    "type": "best_answer",
    "number": 33,
    "question": "What is the accepted method used to measure turbidity?",
    "answer": 4,
    "options": [
      "Candle",
      "Jackson",
      "Light",
      "Nephelometric"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_1",
    "source": "dsa1",
    "type": "select_all",
    "number": 1,
    "question": "The size of a water treatment plant as well as the number and specific types of processes it uses depend on which of the following factors?",
    "answer": [
      1
    ],
    "options": [
      "Cost",
      "Demand by population and industry",
      "Fire Protection needs",
      "Impurities in raw water",
      "Water quality standards"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_2",
    "source": "dsa1",
    "type": "select_all",
    "number": 2,
    "question": "Which of the following tasks are typical duties of a water treatment plant operator?",
    "answer": [
      1
    ],
    "options": [
      "Collect representative samples",
      "Conduct safety inspections",
      "Maintain plant records",
      "Periodic operating checks of equipment",
      "Routine preventative maintenance"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_3",
    "source": "dsa1",
    "type": "select_all",
    "number": 3,
    "question": "What are the safety responsibilities of an operator?",
    "answer": [
      1
    ],
    "options": [
      "Be aware of safety hazards",
      "Be a part of an active safety program",
      "And ensure everyone takes safety seriously",
      "Understand why the safety procedures exist"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_4",
    "source": "dsa1",
    "type": "select_all",
    "number": 4,
    "question": "Possible sources of groundwater contamination include which of the following?",
    "answer": [
      1
    ],
    "options": [
      "Agriculture drainage systems",
      "A surface runoff into wells",
      "Evapotranspiration systems",
      "Sea water intrusion",
      "Septic tank seepage"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_5",
    "source": "dsa1",
    "type": "select_all",
    "number": 5,
    "question": "What conditions are favorable for the rapid growth of algae blooms?",
    "answer": [
      3
    ],
    "options": [
      "Dissolved oxygen",
      "Hardness",
      "Nutrients",
      "pH",
      "Temperature"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_6",
    "source": "dsa1",
    "type": "select_all",
    "number": 6,
    "question": "What are the basic objectives that control the operation of water treatment plants?",
    "answer": [
      1
    ],
    "options": [
      "Production of a safe drinking water",
      "Production of an aesthetically pleasing and drinking water",
      "Production of drinking water at a reasonable cost",
      "Providing opportunities for professional advancement"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_7",
    "source": "dsa1",
    "type": "select_all",
    "number": 7,
    "question": "Which of the following water quality problems may be related to algal blooms?",
    "answer": [
      1
    ],
    "options": [
      "Dissolved oxygen depletion",
      "Reduced chlorination efficiency",
      "Reduced water temperature",
      "Shorten filter runs",
      "Taste and odor problems"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_8",
    "source": "dsa1",
    "type": "select_all",
    "number": 8,
    "question": "What is the impact from increased organic loads on the water treatment plant resulting from algal blooms?",
    "answer": [
      1
    ],
    "options": [
      "High trihalomethane levels",
      "Increased chlorine demand",
      "Increase color",
      "Increased public confidence in water supply",
      "Increased water treatment costs"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_9",
    "source": "dsa1",
    "type": "select_all",
    "number": 9,
    "question": "On domestic water supply reservoirs that develop anaerobic zones what water quality indicators should be monitored?",
    "answer": [
      3
    ],
    "options": [
      "Biochemical oxygen demand (BOD)",
      "Hardness",
      "Hydrogen sulfide",
      "Iron",
      "Manganese"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_10",
    "source": "dsa1",
    "type": "select_all",
    "number": 10,
    "question": "Which of the following are commonly used coagulation chemicals?",
    "answer": [
      1
    ],
    "options": [
      "Alum",
      "Hypochlorites",
      "Metallic salts",
      "Polymers",
      "Sodium chloride"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_11",
    "source": "dsa1",
    "type": "select_all",
    "number": 11,
    "question": "Which of the following factors are important when evaluating jar test results?",
    "answer": [
      1
    ],
    "options": [
      "Amount of floc formed",
      "Clarity of water above settled floc",
      "Clarity of water between floc particles",
      "Floc settling rate",
      "Rate of floc formation"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_12",
    "source": "dsa1",
    "type": "select_all",
    "number": 12,
    "question": "Operators of the coagulation-flocculation process will be exposed to which of the following potential safety hazards?",
    "answer": [
      1
    ],
    "options": [
      "Confined spaces",
      "Electrical equipment",
      "Rotating mechanical equipment",
      "Slippery surfaces",
      "Chemicals"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_13",
    "source": "dsa1",
    "type": "select_all",
    "number": 13,
    "question": "Which terms are adjusted in the enhanced coagulation process?",
    "answer": [
      2
    ],
    "options": [
      "Basic contents",
      "Coagulation dosage",
      "Detention time",
      "Mixing",
      "pH"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_14",
    "source": "dsa1",
    "type": "select_all",
    "number": 14,
    "question": "What is the purpose of presedimentation facilities?",
    "answer": [
      2
    ],
    "options": [
      "Avoid the need for sedimentation basins",
      "Even out fluctuations in the concentration of suspended particles",
      "Prevent solids from settling out before sedimentation",
      "Provide an equalizing basin",
      "Reduce the solids removal load at the water treatment plant"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_15",
    "source": "dsa1",
    "type": "select_all",
    "number": 15,
    "question": "Why is short circuiting undesirable in a sedimentation basin?",
    "answer": [
      1
    ],
    "options": [
      "Causes shorter contact times",
      "Causes shorter reaction times",
      "Causes shorter settling times",
      "Minimizes density currents",
      "Minimizes temperature differences"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_16",
    "source": "dsa1",
    "type": "select_all",
    "number": 16,
    "question": "What kinds of changes cause instability in solids contact units?",
    "answer": [
      2
    ],
    "options": [
      "Dissolved Oxygen (DO)",
      "Flowrate",
      "pH",
      "Temperature",
      "Turbidity"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_17",
    "source": "dsa1",
    "type": "select_all",
    "number": 17,
    "question": "Which water quality indicators should be monitored in the normal operation of the sedimentation process?",
    "answer": [
      4
    ],
    "options": [
      "Chlorine residual",
      "Coliforms",
      "Suspended solids",
      "Temperature",
      "Turbidity"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_18",
    "source": "dsa1",
    "type": "select_all",
    "number": 18,
    "question": "Filter removal of turbidity depends on which of the following factors?",
    "answer": [
      1
    ],
    "options": [
      "Chemical characteristics of the water",
      "Filter type",
      "Nature of suspended particulates",
      "Operation of the filter",
      "Types of pretreatment"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_19",
    "source": "dsa1",
    "type": "select_all",
    "number": 19,
    "question": "Which of the following characteristics are used to classify filter media?",
    "answer": [
      1
    ],
    "options": [
      "Effective size",
      "Filterability",
      "Hardness",
      "Specific gravity",
      "Uniformity coefficient"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_20",
    "source": "dsa1",
    "type": "select_all",
    "number": 20,
    "question": "How can an operator determine if a filter is not completely clean after backwashing?",
    "answer": [
      2
    ],
    "options": [
      "Backwash rate is too low",
      "Initial head loss is too high",
      "Length of backwash cycle is too short",
      "Next filter run is too short",
      "Pumping rate is too low"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_21",
    "source": "dsa1",
    "type": "select_all",
    "number": 21,
    "question": "Which of the following items are indicators of abnormal filter conditions?",
    "answer": [
      1
    ],
    "options": [
      "Algae on the walls and media",
      "Media boils during backwash",
      "Media cracking or shrinkage",
      "Mud balls in the filter media",
      "Short filter runs"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_22",
    "source": "dsa1",
    "type": "select_all",
    "number": 22,
    "question": "Which of the following factors influence chlorine disinfection?",
    "answer": [
      1
    ],
    "options": [
      "Microorganisms",
      "pH",
      "Reducing agents",
      "Temperature",
      "Turbidity"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_23",
    "source": "dsa1",
    "type": "select_all",
    "number": 23,
    "question": "Chloramines have proven effective in accomplishing which of the following objectives?",
    "answer": [
      1
    ],
    "options": [
      "Killing or inactivating heterotrophic plate count bacteria",
      "Maintaining a detectable residual throughout the distribution system",
      "Penetrating the biofilm and reducing the potential for coliform regrowth",
      "Reducing taste and order problems",
      "Reducing the formation of trihalomethanes and other disinfection by products."
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_24",
    "source": "dsa1",
    "type": "select_all",
    "number": 24,
    "question": "What are the most probable causes of a drop in chlorine level in treated water?",
    "answer": [
      3
    ],
    "options": [
      "Change in alkalinity",
      "Coliform regrowth",
      "A drop in chlorine feed rate",
      "Increase in chlorine demand",
      "Increase in coliform level"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_25",
    "source": "dsa1",
    "type": "select_all",
    "number": 25,
    "question": "Which of the following items should be included in all chlorine safety programs?",
    "answer": [
      1
    ],
    "options": [
      "Emergency procedures for chlorine leaks and first aid",
      "Maintenance and calibration program for safety devices and equipment",
      "Periodic hands on training using safety equipment",
      "Plant tours for police and fire departments",
      "Written rules and specific safety procedures"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_26",
    "source": "dsa1",
    "type": "select_all",
    "number": 26,
    "question": "Which of the following physical factors influence the rate of corrosion?",
    "answer": [
      1
    ],
    "options": [
      "Flow velocity",
      "Soil moisture",
      "Stray electric current",
      "Temperature of water",
      "Type of coatings"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_27",
    "source": "dsa1",
    "type": "select_all",
    "number": 27,
    "question": "How can operators determine if corrosion problems exist?",
    "answer": [
      1
    ],
    "options": [
      "Chemical tests on the water",
      "Consumer complaints",
      "Examine materials removed from distribution system",
      "Flow tests",
      "Increasing number of leaks"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_28",
    "source": "dsa1",
    "type": "select_all",
    "number": 28,
    "question": "Which of the following are monitored as corrosion related water quality indicators?",
    "answer": [
      1
    ],
    "options": [
      "Alkalinity",
      "Conductivity",
      "Hardness",
      "pH",
      "Temperature"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_29",
    "source": "dsa1",
    "type": "select_all",
    "number": 29,
    "question": "What are some of the damaging effects for a water utility resulting from a taste and odour episode?",
    "answer": [
      2
    ],
    "options": [
      "Additional regulatory surveillance",
      "Funding restrictions",
      "Increased public relations problems",
      "Increased sales of bottled water",
      "Loss of public confidence"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_30",
    "source": "dsa1",
    "type": "select_all",
    "number": 30,
    "question": "Which of the following are locations that have been identified as possible sources of tastes and odors?",
    "answer": [
      1
    ],
    "options": [
      "Consumer plumbing",
      "Conveyance facilities",
      "Finished water storage reservoirs",
      "Raw water sources",
      "Treatment plants"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_31",
    "source": "dsa1",
    "type": "select_all",
    "number": 31,
    "question": "The success of chlorination as a taste and odor treatment will depend on which factors?",
    "answer": [
      1
    ],
    "options": [
      "Contact time",
      "Dosage applied",
      "Reservoir stratification",
      "Seriousness of the problem",
      "Type of odour"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_32",
    "source": "dsa1",
    "type": "select_all",
    "number": 32,
    "question": "What precautions should be taken when handling power activated carbon (PAC)?",
    "answer": [
      1
    ],
    "options": [
      "Follow confined space procedures",
      "Store PAC bags on wooden pallets",
      "Store PAC away from flammable materials",
      "Use dust control equipment",
      "Wear protective clothing"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_33",
    "source": "dsa1",
    "type": "select_all",
    "number": 33,
    "question": "Where is turbidity commonly monitored in a water treatment plant?",
    "answer": [
      2
    ],
    "options": [
      "Backwash water",
      "Each unit process",
      "Finished water",
      "Individual filters",
      "Raw water"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_34",
    "source": "dsa1",
    "type": "select_all",
    "number": 34,
    "question": "What are the purposes of clearwells?",
    "answer": [
      1
    ],
    "options": [
      "Act as a buffer that prevents frequent on/off cycling",
      "Allow clarification of water by providing time for a particulates to settle out",
      "Allow filling when demands are low to compensate for peak periods",
      "Permit planned changes in treatment plant operation",
      "Provide operational storage to average out high/low flow demands"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_35",
    "source": "dsa1",
    "type": "select_all",
    "number": 35,
    "question": "Which factors can lead to poor quality laboratory data?",
    "answer": [
      1
    ],
    "options": [
      "Calculation mistakes",
      "Deteriorated reagents",
      "Neatly recorded results",
      "Poor operating instruments",
      "Sloppy technique"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_36",
    "source": "dsa1",
    "type": "select_all",
    "number": 36,
    "question": "Which of the following hazards could be encountered in a laboratory?",
    "answer": [
      1
    ],
    "options": [
      "Burns",
      "Drowning",
      "Electric shock",
      "Explosions",
      "Hazardous material"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_37",
    "source": "dsa1",
    "type": "select_all",
    "number": 37,
    "question": "Grab samples should be used to measure which of the following water quality indicators?",
    "answer": [
      1
    ],
    "options": [
      "Chlorine residual",
      "Coliform bacteria",
      "Dissolved gases",
      "pH",
      "Temperature"
    ],
    "tags": []
  },
  {
    "id": "dsa1_select_all_38",
    "source": "dsa1",
    "type": "select_all",
    "number": 38,
    "question": "An alkalinity determination is needed when calculating chemical dosages used in what water treatment processes?",
    "answer": [
      1
    ],
    "options": [
      "Coagulation",
      "Filtration",
      "Flocculation",
      "Settling",
      "Softening"
    ],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_1",
    "source": "dsa1",
    "type": "flashcard",
    "number": 1,
    "question": "Why do intake structures at water treatment plants have screens?",
    "answer": "To prevent leaves and other debris from clogging or damaging pumps, pipes, and other pieces of equipment",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_2",
    "source": "dsa1",
    "type": "flashcard",
    "number": 2,
    "question": "Why should a water treatment plant operator be present when a new plant is being constructed?",
    "answer": "To be familiar with the plant layout including piping, equipment, and machinery and their intended operation and to bring up potential operating or maintenance issues",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_3",
    "source": "dsa1",
    "type": "flashcard",
    "number": 3,
    "question": "What is the reason for keeping adequate reliable records?",
    "answer": "To record the effectiveness of your operation required by regulatory agencies",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_4",
    "source": "dsa1",
    "type": "flashcard",
    "number": 4,
    "question": "How does the water hydraulic cycle work?",
    "answer": "The transfer of moisture from the sea to land and back to the sea again, evaporates, precipitates, transpirates",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_5",
    "source": "dsa1",
    "type": "flashcard",
    "number": 5,
    "question": "What items should be considered before selecting a location and constructing a water supply intake in a river or stream?",
    "answer": "The stream bottom the degree of scour and settling of silt, intake design can it handle flooding, heavy silting, ice, adverse runoff conditions",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_6",
    "source": "dsa1",
    "type": "flashcard",
    "number": 6,
    "question": "Who should conduct sanitary surveys, why?",
    "answer": "People trained and competent in that field of engineering, epidemiology of waterborne diseases",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_7",
    "source": "dsa1",
    "type": "flashcard",
    "number": 7,
    "question": "Who must comply with the Safe Drinking Water Act (SDWA) regulations?",
    "answer": "All public water systems must comply with SDWA regulations",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_8",
    "source": "dsa1",
    "type": "flashcard",
    "number": 8,
    "question": "What methods are used to treat domestic water delivered from water supply reservoirs?",
    "answer": "Disinfection only, to direct filtration, to complete conventional treatment which could include softening and activated carbon filtration, membrane filtration systems",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_9",
    "source": "dsa1",
    "type": "flashcard",
    "number": 9,
    "question": "What is the influence of algal blooms on dissolved oxygen?",
    "answer": "DO content at depths where the bloom occurs increases as a result of photosynthesis, when the algal cells die the oxygen is used in the decomposition by bacteria organisms and DO falls",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_10",
    "source": "dsa1",
    "type": "flashcard",
    "number": 10,
    "question": "How can the desired rate of copper sulfate (CuSO4) application to a reservoir be achieved?",
    "answer": "Considering the speed of the boat the rate the material is being fed from the hopper and pumped into the lake and the area covered by the spray apparatus or the submerged outlet system",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_11",
    "source": "dsa1",
    "type": "flashcard",
    "number": 11,
    "question": "What is the main safety hazard encountered during a reservoir sampling?",
    "answer": "Drowning",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_factsheet_12",
    "source": "dsa1",
    "type": "factsheet",
    "number": 12,
    "question": "Define the following terms; grab sample, reagent, short circuiting:",
    "answer": "A single sample collected at a particular time and place which represents the water at that time and place",
    "options": [
      "A pure chemical substance that is used to make new products or used in tests to measure, detect, or examine other substances",
      "When water entering tanks or basins almost immediately exits, not allowing for adequate detention times or settling"
    ],
    "tags": []
  },
  {
    "id": "dsa1_factsheet_13",
    "source": "dsa1",
    "type": "factsheet",
    "number": 13,
    "question": "What is the difference between coagulation and flocculation processes?",
    "answer": "Coagulation involves adding chemicals and rapid mixing so the suspended particles clump together",
    "options": [
      "Flocculation involves gathering of coagulated clumps into larger floc by gentle mixing to settle out",
      "Coagulation neutralizes the repelling electrical charges"
    ],
    "tags": []
  },
  {
    "id": "dsa1_factsheet_14",
    "source": "dsa1",
    "type": "factsheet",
    "number": 14,
    "question": "What is the purpose of the flocculation process?",
    "answer": "Promote the gathering together of floc for the downstream sedimentation and/or filtration processes",
    "options": [
      "Sedimentation processes are not always required.",
      "Sometimes it's only coagulation, flocculation, filtration"
    ],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_15",
    "source": "dsa1",
    "type": "flashcard",
    "number": 15,
    "question": "What is the basic purpose of the jar test?",
    "answer": "A rough indication of the required dose for your plant, then adjust and fine tune with the actual water treatment plant",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_16",
    "source": "dsa1",
    "type": "flashcard",
    "number": 16,
    "question": "What would you do if you discovered abrupt changes in the source water or filtered water turbidity?",
    "answer": "Signs you should immediately review the performance of the coagulation-flocculation processes",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_17",
    "source": "dsa1",
    "type": "flashcard",
    "number": 17,
    "question": "What are the purposes of the sedimentation process?",
    "answer": "Remove suspended solids that are denser than water to reduce the load on the filters",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_18",
    "source": "dsa1",
    "type": "flashcard",
    "number": 18,
    "question": "List 4 zones which a typical sedimentation basin can be divided:",
    "answer": "Inlet zone, settling zone, sludge zone, and outlet zone",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_19",
    "source": "dsa1",
    "type": "flashcard",
    "number": 19,
    "question": "What problems are created when the sludge build up on the bottom of the sedimentation tank becomes too great? Think Q=VA.",
    "answer": "The depth is reduced thus causing high flow velocities sludge scouring and a decrease in process efficiency, cross sectional area decreases so velocity increases",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_20",
    "source": "dsa1",
    "type": "flashcard",
    "number": 20,
    "question": "Why should water treatment plants have at least 2 sedimentation basins?",
    "answer": "To allow for maintenance, cleaning, and inspection of a basin without requiring a complete shutdown",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_21",
    "source": "dsa1",
    "type": "flashcard",
    "number": 21,
    "question": "How is the approximate process removal efficiency of a sedimentation basin determined?",
    "answer": "Measurement of turbidity levels at the sedimentation basin inlet and outlet",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_22",
    "source": "dsa1",
    "type": "flashcard",
    "number": 22,
    "question": "What is the primary purpose of the filtration process?",
    "answer": "For disinfection, removal of impurities consisting of suspended silts, clays, colloids, biological forms (bacteria and plankton), and floc from the water",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_23",
    "source": "dsa1",
    "type": "flashcard",
    "number": 23,
    "question": "What is the primary purpose of using activated carbon (granular) as filter media?",
    "answer": "Remove taste and odour causing compounds as well as other trace organics",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_24",
    "source": "dsa1",
    "type": "flashcard",
    "number": 24,
    "question": "How frequently should the performance of the filtration process be evaluated?",
    "answer": "Routine basis at least once per 8 hour shift more frequently when the water quality is fluctuating, turbidity levels should be checked every 2 hours",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_25",
    "source": "dsa1",
    "type": "flashcard",
    "number": 25,
    "question": "What 4 types of filtration can be used to meet the requirements of the Surface Water Treatment Rule?",
    "answer": "Conventional, direct, slow sand, diatomaceous earth",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_26",
    "source": "dsa1",
    "type": "flashcard",
    "number": 26,
    "question": "What's the difference between disinfection and sterilization?",
    "answer": "Disinfection is the selective destruction or inactivation of a pathogenic organism, while sterilization is the complete destruction of all organisms",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_27",
    "source": "dsa1",
    "type": "flashcard",
    "number": 27,
    "question": "How does the temperature of the water influence disinfection?",
    "answer": "Relatively cold water requires longer disinfection time or greater quantities of disinfectants, chemical reactions are slower",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_28",
    "source": "dsa1",
    "type": "flashcard",
    "number": 28,
    "question": "How is the chlorine demand determined?",
    "answer": "Chlorine Demand (mg/L) = Chlorine Dose - Chlorine Residual",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_29",
    "source": "dsa1",
    "type": "flashcard",
    "number": 29,
    "question": "How should valves on chlorine containers be opened?",
    "answer": "A max 6\" wrench to unseat, strike the wrench with the heel of your hand, 1 turn is maximum discharge",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_30",
    "source": "dsa1",
    "type": "flashcard",
    "number": 30,
    "question": "What is the purpose of evaporators?",
    "answer": "To convert liquid chlorine to gaseous chlorine for the use by gas chlorinators",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_31",
    "source": "dsa1",
    "type": "flashcard",
    "number": 31,
    "question": "If chlorine is escaping from a cylinder, what would you do?",
    "answer": "Turn the cylinder so that the chlorine escapes as a gas, not a liquid",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_32",
    "source": "dsa1",
    "type": "flashcard",
    "number": 32,
    "question": "What properties make chlorine so hazardous?",
    "answer": "Extremely toxic and corrosive in moist atmospheres",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_33",
    "source": "dsa1",
    "type": "flashcard",
    "number": 33,
    "question": "Why is ozone normally generated on site?",
    "answer": "Very unstable and decomposes to the element oxygen in a short time",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_factsheet_34",
    "source": "dsa1",
    "type": "factsheet",
    "number": 34,
    "question": "Define the following terms break point chlorination and pathogenic organisms:",
    "answer": "Breakpoint chlorination- addition of chlorine until demand has been satisfied, any further will be free chlorine",
    "options": [
      "Pathogenic organisms- bacteria viruses or cysts capable of causing diseases like:",
      "Giardiasis, cryptosporidius, typhoid, cholera, dysentery"
    ],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_35",
    "source": "dsa1",
    "type": "flashcard",
    "number": 35,
    "question": "What is corrosion?",
    "answer": "Decomposition or destruction of a material such as metal or cement as it reacts with water",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_36",
    "source": "dsa1",
    "type": "flashcard",
    "number": 36,
    "question": "How do dissolved solids in water influence corrosion?",
    "answer": "Dissolve solids increase corrosion by increasing the electrical conductivity of the water",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_37",
    "source": "dsa1",
    "type": "flashcard",
    "number": 37,
    "question": "What is the impact of calcium carbonate on corrosion?",
    "answer": "A thin film or coating can drastically inhibit corrosion",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_38",
    "source": "dsa1",
    "type": "flashcard",
    "number": 38,
    "question": "What is a tubercle?",
    "answer": "A small protective crust of rust that builds up over a pit caused by the loss of metal from corrosion",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_39",
    "source": "dsa1",
    "type": "flashcard",
    "number": 39,
    "question": "How can water be tested to determine if it is undersaturated or supersaturated with calcium carbonate?",
    "answer": "The marble Test and Langelier Index are used to determine if water is undersaturated or supersaturated with calcium carbonate",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_40",
    "source": "dsa1",
    "type": "flashcard",
    "number": 40,
    "question": "How can the corrosivity of water be reduced?",
    "answer": "Treat the water so it's saturated or slightly supersaturated with calcium carbonate (CaCO3)",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_41",
    "source": "dsa1",
    "type": "flashcard",
    "number": 41,
    "question": "What are the most common types of water quality complaints received by a water utility?",
    "answer": "Taste and odours",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_42",
    "source": "dsa1",
    "type": "flashcard",
    "number": 42,
    "question": "How can the use of copper sulfate in a reservoir cause taste and odour problems?",
    "answer": "It could disrupt the natural balance of diversified plankton communities and allow an objectionable organism to predominate",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_43",
    "source": "dsa1",
    "type": "flashcard",
    "number": 43,
    "question": "How is the frequency of flushing mains in water distribution systems determined?",
    "answer": "By records of complaints and water quality tests from previous years",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_44",
    "source": "dsa1",
    "type": "flashcard",
    "number": 44,
    "question": "List the 2 broad categories of taste and odour treatment methods:",
    "answer": "Removal and destruction",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_45",
    "source": "dsa1",
    "type": "flashcard",
    "number": 45,
    "question": "What types of taste and odour producing waste have been treated successfully by using chlorine dioxide?",
    "answer": "Industrial pollution especially in cases where chlorine has made the problem worse",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_46",
    "source": "dsa1",
    "type": "flashcard",
    "number": 46,
    "question": "What safety precautions should be exercised when cleaning a tank that stores powdered activated carbon?",
    "answer": "Confined space procedures, open tank with forced positive fresh air",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_47",
    "source": "dsa1",
    "type": "flashcard",
    "number": 47,
    "question": "Where are the water quality samples usually collected to measure compliance with water quality standards?",
    "answer": "Taken at the entry point to the distribution system",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_48",
    "source": "dsa1",
    "type": "flashcard",
    "number": 48,
    "question": "What precautions must be exercised when using air for pneumatic data transmission?",
    "answer": "The air must be dry to prevent condensation in the equipment signal lines and filtered from contaminants",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_49",
    "source": "dsa1",
    "type": "flashcard",
    "number": 49,
    "question": "Why are positive air pressure fans preferred over floor level exhaust fans and chlorine storage facilities?",
    "answer": "If you pull air with chlorine through a fan it will corrode wiring and mechanical parts",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_50",
    "source": "dsa1",
    "type": "flashcard",
    "number": 50,
    "question": "What three factors usually cause treatment processes to fail?",
    "answer": "Raw water quality, operator error, equipment failure",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_51",
    "source": "dsa1",
    "type": "flashcard",
    "number": 51,
    "question": "What is a meniscus?",
    "answer": "The curve on the surface of a liquid in a small tube",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_52",
    "source": "dsa1",
    "type": "flashcard",
    "number": 52,
    "question": "How would you titrate a test solution?",
    "answer": "Addition of a standardized solution slowly until a change is observed called the endpoint",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_53",
    "source": "dsa1",
    "type": "flashcard",
    "number": 53,
    "question": "You may add acid to water or water to acid?",
    "answer": "Think chemicals to a large pool, acid to water",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_54",
    "source": "dsa1",
    "type": "flashcard",
    "number": 54,
    "question": "Why should water not be poured on certain types of fires?",
    "answer": "Pouring water on grease, electrical, or metal fires could cause the hazard to splatter and spread, shock",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_55",
    "source": "dsa1",
    "type": "flashcard",
    "number": 55,
    "question": "Why are proper sampling procedures important?",
    "answer": "To obtain an accurate description of the material or water, a bad sample is pointless data",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_56",
    "source": "dsa1",
    "type": "flashcard",
    "number": 56,
    "question": "What is meant by a representative sample?",
    "answer": "A sample that is nearly identical in content and consistency with the larger body of material or water",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_57",
    "source": "dsa1",
    "type": "flashcard",
    "number": 57,
    "question": "What is the potential adverse effect from chlorination?",
    "answer": "Formation of carcinogenic chlororganic compounds such as chloroform, and other THMs, HAAs",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_58",
    "source": "dsa1",
    "type": "flashcard",
    "number": 58,
    "question": "What are the principal hardness causing ions in water?",
    "answer": "Calcium and magnesium",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_flashcard_59",
    "source": "dsa1",
    "type": "flashcard",
    "number": 59,
    "question": "Why should turbidity be measured in a sample as soon as possible?",
    "answer": "To obtain accurate results the turbidity will settle over time, temperature increase settles faster",
    "options": [],
    "tags": []
  }
];

// For Node.js / module usage
if (typeof module !== "undefined") module.exports = { questions };
