// Water Treatment Study Site — Question Dataset
// Auto-generated by convert.js — do not edit manually
// Source: dsa2.csv
// Generated: 2026-04-25T01:31:39.647Z
// Questions: 148

const questions = [
  {
    "id": "dsa2_true_false_1",
    "source": "dsa2",
    "type": "true_false",
    "number": 1,
    "question": "Both iron and manganese are essential to the growth of many plants and animals, including humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_2",
    "source": "dsa2",
    "type": "true_false",
    "number": 2,
    "question": "Only one cell of iron bacteria is needed to start an infestation of iron bacteria in a well or distribution system.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_3",
    "source": "dsa2",
    "type": "true_false",
    "number": 3,
    "question": "pH is decreased by the removal of carbon dioxide.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "pH is increased by the removal of carbon dioxide"
  },
  {
    "id": "dsa2_true_false_4",
    "source": "dsa2",
    "type": "true_false",
    "number": 4,
    "question": "Fluoride saturators are a special application of a solution feeder.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_5",
    "source": "dsa2",
    "type": "true_false",
    "number": 5,
    "question": "Fluoride solutions are extremely corrosive.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_6",
    "source": "dsa2",
    "type": "true_false",
    "number": 6,
    "question": "Excessively hard water can cause scaling on the inside of pipes and thereby restrict flow.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_7",
    "source": "dsa2",
    "type": "true_false",
    "number": 7,
    "question": "The stability of treated water is determined by measuring the pH and calculating the Langley index.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_8",
    "source": "dsa2",
    "type": "true_false",
    "number": 8,
    "question": "The addition of acid to prevent calcium carbonate scale will accomplish the same things as re arbonation and the addition of polyphosphate.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The addition of acid to prevent calcium carbonate scale will not accomplish the same thing as re carbonation and the addition of polyphosphate"
  },
  {
    "id": "dsa2_true_false_9",
    "source": "dsa2",
    "type": "true_false",
    "number": 9,
    "question": "The feed rates determined by jar tests always produce the exact same results in the actual plant.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The feed rates determined by jar tests do not always produce the exact same results as the actual plant"
  },
  {
    "id": "dsa2_true_false_10",
    "source": "dsa2",
    "type": "true_false",
    "number": 10,
    "question": "The effluent from an ion exchange unit usually will have 0 hardness until the unit needs regeneration.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_11",
    "source": "dsa2",
    "type": "true_false",
    "number": 11,
    "question": "The overwhelming bulk of THM precursors in water are from industrial organic chemicals.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The overwhelming bulk of THM precursors in water are from natural organic compounds not industrial organic chemicals"
  },
  {
    "id": "dsa2_true_false_12",
    "source": "dsa2",
    "type": "true_false",
    "number": 12,
    "question": "When collecting water samples for THM analysis, be sure to collect the sample before the water temperature becomes constant.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "When collecting water samples for THM analysis be sure to allow time for the water temperature to become constant"
  },
  {
    "id": "dsa2_true_false_13",
    "source": "dsa2",
    "type": "true_false",
    "number": 13,
    "question": "The higher the pH of water, the slower the production of THMs.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The higher the pH of the water the faster the production of THMS"
  },
  {
    "id": "dsa2_true_false_14",
    "source": "dsa2",
    "type": "true_false",
    "number": 14,
    "question": "Low levels of arsenic consumed over a long period of time can cause cancer and non cancerous toxic effects on humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_15",
    "source": "dsa2",
    "type": "true_false",
    "number": 15,
    "question": "Electrical conductivity (EC) can usually be correlated directly to arsenic reduction.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Electrical conductivity (EC) cannot be usually correlated directly with arsenic reduction"
  },
  {
    "id": "dsa2_true_false_16",
    "source": "dsa2",
    "type": "true_false",
    "number": 16,
    "question": "All waters contain various amounts of total dissolved solids (TDS), including fresh water.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_17",
    "source": "dsa2",
    "type": "true_false",
    "number": 17,
    "question": "The rate of hydrolysis is accelerated by decreased temperature.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The rate of hydrolysis is accelerated by increased temperature"
  },
  {
    "id": "dsa2_true_false_18",
    "source": "dsa2",
    "type": "true_false",
    "number": 18,
    "question": "The output of a positive displacement pump may be throttled.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The output of a positive displacement pump may not be throttled"
  },
  {
    "id": "dsa2_true_false_19",
    "source": "dsa2",
    "type": "true_false",
    "number": 19,
    "question": "At a minimum, the rate of membrane hydrolysis is at a pH of about 4.7, and it increases with both increasing and decreasing pH.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_20",
    "source": "dsa2",
    "type": "true_false",
    "number": 20,
    "question": "Trash and grit may be disposed of in landfills.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_21",
    "source": "dsa2",
    "type": "true_false",
    "number": 21,
    "question": "Before filling a drained tank after removing sludge, thoroughly disinfect the tank.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_22",
    "source": "dsa2",
    "type": "true_false",
    "number": 22,
    "question": "The application of nitrogen fertilizers causes an increase in soil pH.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The application of nitrogen fertilizers causes a reduction in soil pH"
  },
  {
    "id": "dsa2_true_false_23",
    "source": "dsa2",
    "type": "true_false",
    "number": 23,
    "question": "One person may be permitted to attempt an emergency repair alone.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "One person should never be permitted to attempt an emergency repair alone"
  },
  {
    "id": "dsa2_true_false_24",
    "source": "dsa2",
    "type": "true_false",
    "number": 24,
    "question": "Operators must be familiar with equipment and understand what it is intended to do before developing a preventative maintenance program and maintaining equipment.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_25",
    "source": "dsa2",
    "type": "true_false",
    "number": 25,
    "question": "Check the temperature of a centrifugal pump bearing temperature by hand.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Check the temperature of a centrifugal pump bearing with a thermometer"
  },
  {
    "id": "dsa2_true_false_26",
    "source": "dsa2",
    "type": "true_false",
    "number": 26,
    "question": "Always be sure a centrifugal pump is primed before starting the pump.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_27",
    "source": "dsa2",
    "type": "true_false",
    "number": 27,
    "question": "Diesel engines can be air or water cooled.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_28",
    "source": "dsa2",
    "type": "true_false",
    "number": 28,
    "question": "Never pour water on a chlorine leak because this will only create a bigger problem by enlarging the leak.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_29",
    "source": "dsa2",
    "type": "true_false",
    "number": 29,
    "question": "Analog instruments provide a direct numerical readout.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_30",
    "source": "dsa2",
    "type": "true_false",
    "number": 30,
    "question": "Long detection lags can result in stable processes and good control.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "long detection legs can result in unstable processes and poor control"
  },
  {
    "id": "dsa2_true_false_31",
    "source": "dsa2",
    "type": "true_false",
    "number": 31,
    "question": "Entry into confined spaces is never permitted until the space has been properly ventilated using specially designed forced-air ventilators.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_32",
    "source": "dsa2",
    "type": "true_false",
    "number": 32,
    "question": "Pneumatic instrumentation depends upon a constant source of clean, dry, pressurized air for reliable operation.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_33",
    "source": "dsa2",
    "type": "true_false",
    "number": 33,
    "question": "The fumes from hydrofluorosilicic acid (H2SiF6) can corrode metal and etch glass on protective equipment.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_34",
    "source": "dsa2",
    "type": "true_false",
    "number": 34,
    "question": "In reactions with most metals, hydrochloric acid will produce hydrogen gas.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_35",
    "source": "dsa2",
    "type": "true_false",
    "number": 35,
    "question": "Anhydrous ammonia (gas) may be stored in the same room with chlorine (gas).",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Anohydrous ammonia (gas) may not be stored in the same room with chlorine (gas)"
  },
  {
    "id": "dsa2_true_false_36",
    "source": "dsa2",
    "type": "true_false",
    "number": 36,
    "question": "When working with chlorine, be equipped to control chlorine leaks, which are most often found in the control valve.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_37",
    "source": "dsa2",
    "type": "true_false",
    "number": 37,
    "question": "Ferric chloride is a very corrosive compound and should be treated as you would with any acid.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_38",
    "source": "dsa2",
    "type": "true_false",
    "number": 38,
    "question": "The most common form of iron in solution in groundwater and in water under anaerobic conditions (bottom of a lake or reservoir) is ferric ion.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The most common form of iron in solution in groundwater and in water under anaerobic conditions (bottom of a lake or reservoir) is ferrous iron."
  },
  {
    "id": "dsa2_true_false_39",
    "source": "dsa2",
    "type": "true_false",
    "number": 39,
    "question": "Nitrate represents the least completely oxidized form of nitrogen found in water.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Nitrate represents the most completely oxidized form of nitrogen found in water"
  },
  {
    "id": "dsa2_true_false_40",
    "source": "dsa2",
    "type": "true_false",
    "number": 40,
    "question": "Chloroform is the most common THM found in drinking water.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_41",
    "source": "dsa2",
    "type": "true_false",
    "number": 41,
    "question": "EPA regulations change frequently as new information becomes available.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_42",
    "source": "dsa2",
    "type": "true_false",
    "number": 42,
    "question": "MCLs apply whether the contaminant is from naturally occurring sources or from man-made pollution.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_43",
    "source": "dsa2",
    "type": "true_false",
    "number": 43,
    "question": "The health risk from mercury is less from mercury in fish than simply from waterborne mercury.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The health risk for mercury is greater from mercury in fish than simply waterborne mercury"
  },
  {
    "id": "dsa2_true_false_44",
    "source": "dsa2",
    "type": "true_false",
    "number": 44,
    "question": "The presence of coliform bacteria indicates that other harmful organisms may be present in the water.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_45",
    "source": "dsa2",
    "type": "true_false",
    "number": 45,
    "question": "Tier 1 violations are any situations in which even a brief violation or short term exposure to a contaminant has the potential to cause serious negative effect on human health.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_46",
    "source": "dsa2",
    "type": "true_false",
    "number": 46,
    "question": "No discipline problem ever solves itself, and the sooner you deal with the problem, the better will be the outcome.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_47",
    "source": "dsa2",
    "type": "true_false",
    "number": 47,
    "question": "Written communication is less demanding than oral communication and requires less careful preparation.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Written communication is more demanding than oral communication and requires more careful preparation"
  },
  {
    "id": "dsa2_true_false_48",
    "source": "dsa2",
    "type": "true_false",
    "number": 48,
    "question": "Customer calls are frequently your first indication that something may be wrong.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_49",
    "source": "dsa2",
    "type": "true_false",
    "number": 49,
    "question": "Corrective maintenance, including emergency maintenance, is considered reactive maintenance.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_50",
    "source": "dsa2",
    "type": "true_false",
    "number": 50,
    "question": "The SCADA system allows operators to enhance the efficiency of their water facility by keeping them fully informed and fully in control.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_51",
    "source": "dsa2",
    "type": "true_false",
    "number": 51,
    "question": "The operator should always call to the supervisor's attention unsafe conditions, environment, and equipment or other concerns about the work they are performing.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_52",
    "source": "dsa2",
    "type": "true_false",
    "number": 52,
    "question": "On-the-Job-Training (OJT) is a good way of preventing accidents with an inexperienced operator.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "On-the Job-Training (OJT) is not a good way of presenting accidents with an inexperienced operator"
  },
  {
    "id": "dsa2_best_answer_1",
    "source": "dsa2",
    "type": "best_answer",
    "number": 1,
    "question": "How can the growth of iron bacteria be controlled by caustic soda?",
    "answer": 2,
    "options": [
      "Caustic Soda",
      "Chlorination",
      "Permanganate",
      "Sulfuric Acid"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_2",
    "source": "dsa2",
    "type": "best_answer",
    "number": 2,
    "question": "What is the best way to determine if there is an iron and manganese problem in a water supply?",
    "answer": 4,
    "options": [
      "Collect samples and analyze them for iron and manganese",
      "Consult with local health authorities",
      "Interview concerned homeowners",
      "Look for stained plumbing fixtures in a couple of houses"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_3",
    "source": "dsa2",
    "type": "best_answer",
    "number": 3,
    "question": "What should an operator do when operating an ion exchange unit and iron & manganese start to appear in the treated water?",
    "answer": 4,
    "options": [
      "Inform consumers of the presence of iron and manganese",
      "Keep the unit operating until breakthrough becomes excessive",
      "Notify the regulatory agency or the health department",
      "Regenerate with a brine solution"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_4",
    "source": "dsa2",
    "type": "best_answer",
    "number": 4,
    "question": "What happens if children drink a recommended dose of fluoride?",
    "answer": 3,
    "options": [
      "Bones become stronger",
      "Growth will be stunted",
      "Fewer dental cavities",
      "Perform better in school"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_5",
    "source": "dsa2",
    "type": "best_answer",
    "number": 5,
    "question": "When working with fluoridation systems using a sodium fluoride solution, why is the hardness of the water very important?",
    "answer": 3,
    "options": [
      "Corrosion can be caused by hardness",
      "Pump cavitation is a problem when hardness is present",
      "Scaling can be caused by hardness",
      "Water hammer problems are caused by hardness"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_6",
    "source": "dsa2",
    "type": "best_answer",
    "number": 6,
    "question": "Water hardness is a measure of which item?",
    "answer": 4,
    "options": [
      "Corrosivity of water",
      "Density of water",
      "Penetration power of water",
      "Soap or detergent-consuming power of water"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_7",
    "source": "dsa2",
    "type": "best_answer",
    "number": 7,
    "question": "Why should bagged quicklime never be stored close to combustible materials?",
    "answer": 2,
    "options": [
      "Combustible materials can use lime for fuel when burning",
      "Considerable heat will be generated if the lime gets wet",
      "Heat from a fire could melt the lime",
      "Lime easily catches on fire"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_8",
    "source": "dsa2",
    "type": "best_answer",
    "number": 8,
    "question": "How can an operator prevent scale formation on the filter sand, distribution mains, and household plumbing?",
    "answer": 1,
    "options": [
      "Converting the excess caustic & unprecipitated carbonate ions to soluble forms",
      "implementing a flushing program",
      "Maintaining high water velocities throughout the system",
      "Regular backwashing"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_9",
    "source": "dsa2",
    "type": "best_answer",
    "number": 9,
    "question": "Why are restrictions placed on the locations where THM samples are collected?",
    "answer": 2,
    "options": [
      "Allow for easy access for sample containers",
      "Avoid the possibility of contaminating samples or losing THMS",
      "Protect homeowners from intrusive sample collectors",
      "Provide operators with safe access for sample collection"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_10",
    "source": "dsa2",
    "type": "best_answer",
    "number": 10,
    "question": "Why is the reducing agent left out of some THM sample bottles?",
    "answer": 2,
    "options": [
      "Avoid introducing THM precursors into the sample",
      "Determine the maximum concentrations of TTHMs",
      "Estimate the hourly rate of TTHM formation",
      "Prevent the formation of TTH Mississippi until the sample is delivered to the lab"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_11",
    "source": "dsa2",
    "type": "best_answer",
    "number": 11,
    "question": "What is a major advantage of removing precursors before chlorine is added?",
    "answer": 1,
    "options": [
      "Allows the continued use of free chlorine as a disinfectant",
      "Facilitates the ultimate disposal of the precursors",
      "Option preferred by most water consumers",
      "Promotes the use of chloramination."
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_12",
    "source": "dsa2",
    "type": "best_answer",
    "number": 12,
    "question": "Why are arsenic split-sample analysis performed by a certified laboratory?",
    "answer": 2,
    "options": [
      "Compare the efficiencies of the field test kits",
      "Confirm results from arsenic test kit analysis",
      "Evaluate the time required to perform the analysis",
      "Test the operator's ability to accurately split samples"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_13",
    "source": "dsa2",
    "type": "best_answer",
    "number": 13,
    "question": "What is the most common pretreatment process to remove turbidity and suspended solids?",
    "answer": 3,
    "options": [
      "Chlorination",
      "Coagulation. Flocculation",
      "Filtration",
      "Sedimentation"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_14",
    "source": "dsa2",
    "type": "best_answer",
    "number": 14,
    "question": "What can be applied to inhibit the growth of bacterial slimes and molds on membrane surfaces?",
    "answer": 2,
    "options": [
      "Acetone",
      "Chlorine",
      "Soda ash",
      "Sulfuric acid"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_15",
    "source": "dsa2",
    "type": "best_answer",
    "number": 15,
    "question": "For electrodialysis demineralization, acid addition is part of the pretreatment of the feed water supply to prevent what?",
    "answer": 1,
    "options": [
      "Carbonate scaling",
      "Membrane compaction",
      "Membrane corrosion",
      "Polarization"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_16",
    "source": "dsa2",
    "type": "best_answer",
    "number": 16,
    "question": "What regular activity is the key to speedy sludge drying in a sludge drying bed",
    "answer": 4,
    "options": [
      "Application of a thick layer of sludge",
      "Application of a thin layer of sludge",
      "Removal of the dried portion of sludge",
      "Removal of the water on top of the sludge"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_17",
    "source": "dsa2",
    "type": "best_answer",
    "number": 17,
    "question": "What is the principal advantage to using centrifuges for sludge dewatering?",
    "answer": 1,
    "options": [
      "Density of the sludge cake can be varied",
      "Erosion of surfaces hit by high speed particles",
      "Low energy consumption",
      "Poor performance capacity"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_18",
    "source": "dsa2",
    "type": "best_answer",
    "number": 18,
    "question": "What is an ampere?",
    "answer": 4,
    "options": [
      "Electrical pressure available to cause a flow of current when an circuit is closed",
      "Level of shock provided by a circuit",
      "Measure of the number of phases provided by the current",
      "Unit of electric current or an indication of how hard the electricity is working"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_19",
    "source": "dsa2",
    "type": "best_answer",
    "number": 19,
    "question": "How can an operator determine if a circuit breaker has been tripped?",
    "answer": 1,
    "options": [
      "Breaker handle will be at the midpoint",
      "Lockout/ tagout device is secure",
      "Overload relay is overheated",
      "Strip or wire off fusible metal is melted"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_20",
    "source": "dsa2",
    "type": "best_answer",
    "number": 20,
    "question": "Why should bearing grease be purchased in cartridge form?",
    "answer": 2,
    "options": [
      "Facilitate applying grease",
      "Minimize the chance of getting dirt into the lubricant",
      "Optimize grease storage space",
      "Reduce costs of the purchasing grease"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_21",
    "source": "dsa2",
    "type": "best_answer",
    "number": 21,
    "question": "How can an operator determine if a pump is primed?",
    "answer": 3,
    "options": [
      "Pump is in a good shape",
      "Pump is ready to start",
      "Pump must be completely filled with water",
      "Pump must be properly aligned"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_22",
    "source": "dsa2",
    "type": "best_answer",
    "number": 22,
    "question": "What does a compressor unloader allow the compressor to do?",
    "answer": 4,
    "options": [
      "Central compressed air",
      "Discharge used oils in grease",
      "Release stored air pressure",
      "Start under no load condition"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_23",
    "source": "dsa2",
    "type": "best_answer",
    "number": 23,
    "question": "The purpose of cathodic protection is to prevent what?",
    "answer": 3,
    "options": [
      "Operators from being exposed to toxic gases",
      "Formation of slimes on walkways",
      "Rusting of base metal surfaces",
      "Scaling and deposition of chemicals on metal surfaces"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_24",
    "source": "dsa2",
    "type": "best_answer",
    "number": 24,
    "question": "What is accuracy?",
    "answer": 2,
    "options": [
      "A physical or chemical quantity which is measured and or controlled in a wastewater treatment process",
      "How closely an instrument measures the true or actual value of a process variable",
      "How closely the device can reproduce a given reading or measurement time after time",
      "Smallest change in a process variable able to produce an appropriate response from an instrument"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_25",
    "source": "dsa2",
    "type": "best_answer",
    "number": 25,
    "question": "What is a very precise method of measuring fluctuating water levels?",
    "answer": 1,
    "options": [
      "Bubbler tube",
      "Displacer",
      "Electrical probe",
      "Pump pressure gauge"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_26",
    "source": "dsa2",
    "type": "best_answer",
    "number": 26,
    "question": "What is the \"test\" button on an annunciator panel used for?",
    "answer": 1,
    "options": [
      "Confirm that no alarm lamps have been burned out",
      "Initiate an alarm condition at each alarm site",
      "Perform alarm drills throughout the plant",
      "Verify the noise level of each alarm"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_27",
    "source": "dsa2",
    "type": "best_answer",
    "number": 27,
    "question": "What is the most useful piece of general electrical test equipment?",
    "answer": 4,
    "options": [
      "Battery charger tester",
      "Ground fault tester",
      "Live circuit tester",
      "Multimeter tester"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_28",
    "source": "dsa2",
    "type": "best_answer",
    "number": 28,
    "question": "How can bases be neutralized?",
    "answer": 3,
    "options": [
      "Ammonia",
      "Deionized water",
      "Dilute acids",
      "Strong acids"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_29",
    "source": "dsa2",
    "type": "best_answer",
    "number": 29,
    "question": "Carbon dioxide gas is considered dangerous and can cause what?",
    "answer": 4,
    "options": [
      "Acidic types of skin burns",
      "Cancer",
      "Injury to the eyes",
      "Suffocation due to the lack of oxygen"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_30",
    "source": "dsa2",
    "type": "best_answer",
    "number": 30,
    "question": "Why are high levels of oxygen above 22.5% dangerous?",
    "answer": 3,
    "options": [
      "Cause excessive exertion by operators",
      "Confuse an operator's thinking ability",
      "Increase the possibility of an explosion",
      "Mask the odor of toxic gases"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_31",
    "source": "dsa2",
    "type": "best_answer",
    "number": 31,
    "question": "What type of electric shock protection must be used when operating power tools outdoors?",
    "answer": 1,
    "options": [
      "Ground fault circuit interrupter GFCI",
      "Insulated screwdrivers",
      "Lockout/ tagout",
      "Rubber gloves"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_32",
    "source": "dsa2",
    "type": "best_answer",
    "number": 32,
    "question": "The purpose of a spectrometer calibration curve is to determine \"if the\" what?",
    "answer": 4,
    "options": [
      "Sample has succeeded its holding time",
      "Spectrometer needs recalibration",
      "Spectrometer reagents are deteriorating",
      "Concentration of the water quality indicator contained in a sample"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_33",
    "source": "dsa2",
    "type": "best_answer",
    "number": 33,
    "question": "What causes apparent colour in water?",
    "answer": 4,
    "options": [
      "Dissolved organic substances or certain minerals",
      "Hardness ions",
      "Iron and manganese",
      "Suspended materials (colloidal substances)"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_34",
    "source": "dsa2",
    "type": "best_answer",
    "number": 34,
    "question": "Specific conductance or conductivity is a numerical expression of which term?",
    "answer": 1,
    "options": [
      "Ability of water to conduct an electric current",
      "Ease of which an electric current heats the water sample",
      "Number of total dissolved solids in a water sample",
      "Transmissibility of a sample of water in a pipeline"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_35",
    "source": "dsa2",
    "type": "best_answer",
    "number": 35,
    "question": "The Disinfectants/ Disinfection Byproducts (D/DBP) rule is designed to protect the public from which of the following?",
    "answer": 4,
    "options": [
      "Chlorine",
      "Disease",
      "Disinfectant flavors and odors",
      "Harmful concentrations of disinfectants"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_36",
    "source": "dsa2",
    "type": "best_answer",
    "number": 36,
    "question": "What is the purpose of the Total Coliform Rule (TCR)?",
    "answer": 3,
    "options": [
      "Avoid public exposure to disease-causing organisms associated with wastewater or animal wastes",
      "Eliminate the need to test for protozoa in drinking water",
      "Reduce fecal pathogens to a minimal levels through control of total coliform bacteria",
      "Prevent the risk of illness from disease-causing organisms"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_37",
    "source": "dsa2",
    "type": "best_answer",
    "number": 37,
    "question": "The purpose of the Filter Backwash Recycling Rule (FBRR) is to improve what?",
    "answer": 2,
    "options": [
      "Filter backwash pumping practices to conserve energy and enhance pumping efficiencies",
      "Recycling practices for contamination control, particularly microbial contaminants",
      "Water filtration plant practices for disposing of filter backwash wastewaters",
      "Conserve, recycle, and reclaim, filter backwash practices"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_38",
    "source": "dsa2",
    "type": "best_answer",
    "number": 38,
    "question": "What is the important difference between MCL and MCLG?",
    "answer": 2,
    "options": [
      "MCLG is always established before the MCL",
      "MCLG is nonenforceable and MCL is an enforceable standard",
      "MCLG is preferred by regulatory agencies in lieu of the MCL",
      "MCL is always lower than the MCLG"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_39",
    "source": "dsa2",
    "type": "best_answer",
    "number": 39,
    "question": "What causes backflow situations in distribution systems?",
    "answer": 2,
    "options": [
      "Defective clearwell safety valves",
      "Either back pressure or back siphonage",
      "Failure of the filter backwash system",
      "Malfunctioning distribution system sampling stations"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_40",
    "source": "dsa2",
    "type": "best_answer",
    "number": 40,
    "question": "What is the National Terrorism Advisory System?",
    "answer": 3,
    "options": [
      "Group with instructions to broadcast warnings of terrorist activity-",
      "Network of agents throughout the world that monitor the potential for terrorist activity",
      "System used to issue informal, detailed alerts about specific or credible terrorist threats",
      "Terrorist detection system programmed to alert water utility agencies"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_41",
    "source": "dsa2",
    "type": "best_answer",
    "number": 41,
    "question": "What is an acute toxic agent?",
    "answer": 2,
    "options": [
      "Bioaccumulates in the system of a susceptible individual",
      "Causes injury quickly",
      "Causes injury to occur over an extended period of exposure",
      "Ingested by an individual"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_42",
    "source": "dsa2",
    "type": "best_answer",
    "number": 42,
    "question": "If a contamination of the water supply is discovered, what is the immediate concern?",
    "answer": 3,
    "options": [
      "Flushing the contaminant out of the system",
      "Protection of the source water",
      "Safety of the public",
      "Source of the contaminant"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_43",
    "source": "dsa2",
    "type": "best_answer",
    "number": 43,
    "question": "What is the purpose of the Safety Data Sheet (SDS)?",
    "answer": 1,
    "options": [
      "Readily available reference document that includes complete information on the hazardous substance",
      "Protect operators from overexposure to hazardous atmospheres",
      "Protect operators from exposure to hazardous substances",
      "Require manufacturers to submit safety information upon delivery of a hazardous substance"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_1",
    "source": "dsa2",
    "type": "select_all",
    "number": 1,
    "question": "Why is the presence of iron and manganese in drinking water objectable?",
    "answer": [
      1,
      2,
      3,
      5
    ],
    "options": [
      "Clothes laundered in the water may come out stained",
      "Iron and manganese promote the growth of iron bacteria",
      "Plumbing fixtures, bathtubs, and sinks may become stained",
      "The water is very corrosive",
      "They create slimes that cause foul flavors and odors"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_2",
    "source": "dsa2",
    "type": "select_all",
    "number": 2,
    "question": "What can be added to increase the pH of water being treated with a continuous regeneration (CR) manganese green sand plant?",
    "answer": [
      2,
      4
    ],
    "options": [
      "Muriatic acid",
      "Sodium carbonate",
      "Sodium chloride",
      "Sodium hydroxide",
      "Sulfuric acid"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_3",
    "source": "dsa2",
    "type": "select_all",
    "number": 3,
    "question": "How can an operator minimize red water or dirty water problems and complaints?",
    "answer": [
      1,
      2,
      4,
      5
    ],
    "options": [
      "Deliver stable (noncorrosive) water to the distribution system",
      "Ensure the water pumped into the distribution system contains a little to no iron and manganese",
      "Keep the health department informed of the water quality conditions",
      "Maintain a free chlorine residual in all water throughout the distribution system",
      "Provide adequate treatment to control iron and manganese"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_4",
    "source": "dsa2",
    "type": "select_all",
    "number": 4,
    "question": "What should warning system alarms at fluoridation plants indicate?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Downtime measured by a time meter",
      "High or low fluoride levels",
      "Low injection water pressure",
      "Low water flow in the main pipeline",
      "Power outages"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_5",
    "source": "dsa2",
    "type": "select_all",
    "number": 5,
    "question": "Which items should be checked before startup of a chemical feeder system?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Safety equipment such as eye wash showers face Shields gloves vents are in place and functional",
      "Check the operation of alarms and safety shut offs",
      "Confirm the safety guards are in place",
      "Examine the operation of all auxiliary equipment; dust collectors, fans, cooling water, mixing water",
      "Record all important nameplate data and place it in the plant files for future reference"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_6",
    "source": "dsa2",
    "type": "select_all",
    "number": 6,
    "question": "How can an operator come in contact with fluoride?",
    "answer": [
      1,
      2,
      3,
      5
    ],
    "options": [
      "Eye contact",
      "Ingestion",
      "Inhalation",
      "Noise exposure",
      "Skin contact"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_7",
    "source": "dsa2",
    "type": "select_all",
    "number": 7,
    "question": "What undesirable effects are caused by excessive hardness in water?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Damage in some industrial processes",
      "Deposition of scale in boilers",
      "Formation of soap curds",
      "Increased use of soap",
      "Objectionable flavors"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_8",
    "source": "dsa2",
    "type": "select_all",
    "number": 8,
    "question": "Which items are limitations of the ion exchange softening process?",
    "answer": [
      2,
      4,
      5
    ],
    "options": [
      "Formation of hardness scale in water mains",
      "Increase in sodium content of softened water",
      "Product water with 0 hardness",
      "Ultimate disposal of rinse water",
      "Ultimate disposal of spent brine"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_9",
    "source": "dsa2",
    "type": "select_all",
    "number": 9,
    "question": "Which items should an operator check when troubleshooting the operation of the backwash stage of an ion exchange softener?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Check for adequate flow rates",
      "Check for excessive flow rates to prevent washing resin from the unit",
      "Check for higher than normal head loss",
      "Check the condition of the resin by visually inspecting the top layer of the bed",
      "Check the timer to make sure the unit is washed for the required length of time"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_10",
    "source": "dsa2",
    "type": "select_all",
    "number": 10,
    "question": "Which treatment processes are available to remove THM's after they have been formed?",
    "answer": [
      1,
      2,
      4
    ],
    "options": [
      "Adsorption",
      "Aeration",
      "Filtration",
      "Oxidation",
      "Sedimentation"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_11",
    "source": "dsa2",
    "type": "select_all",
    "number": 11,
    "question": "Which oxidation processes may remove or modify THM precursors?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Chlorine dioxide",
      "Hydrogen peroxide",
      "Ozone",
      "Ozone/ Ultraviolet",
      "Permanganate"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_12",
    "source": "dsa2",
    "type": "select_all",
    "number": 12,
    "question": "Which Best Available Technology (BAT) processes are available for treating arsenic?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Activated alumina",
      "Coagulation/ Filtration",
      "Ion exchange",
      "Oxidation filtration",
      "Reverse osmosis"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_13",
    "source": "dsa2",
    "type": "select_all",
    "number": 13,
    "question": "What technologies are used by POU and POE devices to remove arsenic from drinking water?",
    "answer": [
      1,
      4,
      5
    ],
    "options": [
      "Activated alumina",
      "Aeration",
      "Blending",
      "Iron-based sorbents",
      "Reverse osmosis"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_14",
    "source": "dsa2",
    "type": "select_all",
    "number": 14,
    "question": "Which methods can be used to remove minerals from water?",
    "answer": [
      1,
      2,
      3,
      4
    ],
    "options": [
      "Distillation",
      "Electrodialysis",
      "Ion exchange",
      "Reverse osmosis",
      "Thawing"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_15",
    "source": "dsa2",
    "type": "select_all",
    "number": 15,
    "question": "Nanofiltration membranes are used for demineralization to reject which terms?",
    "answer": [
      3,
      4,
      5
    ],
    "options": [
      "Alkalinity",
      "Corrosivity",
      "Hardness",
      "TDS",
      "THM formation potential"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_16",
    "source": "dsa2",
    "type": "select_all",
    "number": 16,
    "question": "Which constituents, in feedwater to a reverse osmosis unit require pretreatment to prevent scaling?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Carbonates",
      "Ferric iron",
      "Hydrogen sulfide",
      "Silica",
      "Sulfate"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_17",
    "source": "dsa2",
    "type": "select_all",
    "number": 17,
    "question": "Which commonly used chemicals require special handling in reverse osmosis plant operation?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Acids",
      "Chlorine",
      "Citric acid",
      "Formaldehyde",
      "Sodium hexametaphosphate"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_18",
    "source": "dsa2",
    "type": "select_all",
    "number": 18,
    "question": "What methods are used to dispose of sludges and brines produced at water treatment plants?",
    "answer": [
      1,
      2,
      5
    ],
    "options": [
      "Usually dewatered sludges deposited in landfills",
      "Spread on land",
      "Storm drains",
      "Storm sewers",
      "Wastewater collection systems (sewers)"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_19",
    "source": "dsa2",
    "type": "select_all",
    "number": 19,
    "question": "When recycling drainage waters through a water treatment plant, exercising extreme caution will help avoid contributing to which conditions?",
    "answer": [
      2,
      3,
      4
    ],
    "options": [
      "Excessive solids loading",
      "Flavour and odour problems",
      "Health hazards",
      "Operational problems",
      "Plant flow overloads"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_20",
    "source": "dsa2",
    "type": "select_all",
    "number": 20,
    "question": "Which factors could cause voltage imbalance?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Changing energy demands",
      "Circuit Breakers",
      "High-resistance contacts",
      "Loose connections",
      "Motor starters"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_21",
    "source": "dsa2",
    "type": "select_all",
    "number": 21,
    "question": "which items could be the cause of an electric motor ?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Moisture",
      "Overload",
      "Poor design",
      "Voltage",
      "Wear"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_22",
    "source": "dsa2",
    "type": "select_all",
    "number": 22,
    "question": "Which items are possible causes of pump misalignment?",
    "answer": [
      1,
      3,
      4
    ],
    "options": [
      "Bolts loosening",
      "Change in suction conditions",
      "Foundations settling unevenly",
      "Piping changing position",
      "Water cavitation"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_23",
    "source": "dsa2",
    "type": "select_all",
    "number": 23,
    "question": "Which items are types of pump operating troubles?",
    "answer": [
      2,
      3,
      4,
      5
    ],
    "options": [
      "Excessive discharge flows",
      "High power requirements",
      "Noisy pump",
      "Pump will not start",
      "Reduced rate of discharge"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_24",
    "source": "dsa2",
    "type": "select_all",
    "number": 24,
    "question": "What could cause a reduced rate of discharge from a pump?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Air in the water",
      "Stuck or clogged check valves",
      "Discharge head too high",
      "Clogged impeller",
      "Greater than anticipated suction lift"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_25",
    "source": "dsa2",
    "type": "select_all",
    "number": 25,
    "question": "Which maintenance procedures should be performed on compressors?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Clean the cylinder or casing fins weekly",
      "Drain the condensate (condensed water) from the air receiver",
      "Inspect the suction filter of the compressor regularly",
      "Lubricate the compressor regularly",
      "Test the safety valves"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_26",
    "source": "dsa2",
    "type": "select_all",
    "number": 26,
    "question": "Which items are examples of modulating control systems for water treatment process variables?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Chlorine residual analyzer/ controller",
      "Continuous level control of process basins",
      "Flow-paced chemical feeders",
      "Pressure or flow regulating valves",
      "Variable-speed pumping systems for flow/ level control"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_27",
    "source": "dsa2",
    "type": "select_all",
    "number": 27,
    "question": "Which gases may develop explosive gas mixtures when combined with air?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Gasoline vapors",
      "Hydrogen",
      "Manufactured fuel gas",
      "Methane",
      "Natural gas"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_28",
    "source": "dsa2",
    "type": "select_all",
    "number": 28,
    "question": "Which items can cause electronic instrument problems?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Excessive heat",
      "Static electricity",
      "Temporary power failures",
      "Tripped panel circuit breakers",
      "Voltage surges; lightning"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_29",
    "source": "dsa2",
    "type": "select_all",
    "number": 29,
    "question": "Which items are critical preventative maintenance measures for instrumentation systems?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Bleed pneumatic systems regularly",
      "Do not lubricate tweak fix calibrate or modify arbitrarily",
      "Keep instrument components clean on the outside and closed against contamination",
      "Keep recorder pins and charts functioning as desired by frequent checking and service",
      "Protect all instrumentation from moisture, vibration, and mechanical shock"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_30",
    "source": "dsa2",
    "type": "select_all",
    "number": 30,
    "question": "Which items must an operator know in order to safely handle chemicals?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "The tendency of chemicals to form an arch in a storage bin",
      "Know how to feed the chemicals",
      "Know how to make up solutions",
      "Know how to store chemicals",
      "Understand the fire risk associated with each chemical"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_31",
    "source": "dsa2",
    "type": "select_all",
    "number": 31,
    "question": "Which bases used in water treatment are flammable or explosive?",
    "answer": [
      1,
      2,
      3
    ],
    "options": [
      "Ammonia",
      "Caustic soda",
      "Hypochlorite compounds",
      "Quicklime",
      "Soda ash"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_32",
    "source": "dsa2",
    "type": "select_all",
    "number": 32,
    "question": "Which safety precautions should be taken when handling most salts used in water treatment plants?",
    "answer": [
      1,
      3,
      5
    ],
    "options": [
      "Eye protection",
      "Hard hat",
      "Respiratory protection",
      "Steel-toed shoes",
      "Ventilation"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_33",
    "source": "dsa2",
    "type": "select_all",
    "number": 33,
    "question": "Which steps or tasks are recommended before entry into a confined space?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Empty, flush, or purge the space of any harmful substances",
      "Identify and isolate any lines that contain harmful substances to the work area",
      "If an atmosphere hazard is possible use portable blowers to further ventilate the area",
      "Monitor the atmosphere to determine if dangerous air contamination and/ or oxygen deficiency exists",
      "Record the atmospheric test results and keep them at the site throughout the work period"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_34",
    "source": "dsa2",
    "type": "select_all",
    "number": 34,
    "question": "Which steps must be completed in order to prepare a spectrophotometer calibration curve?",
    "answer": [
      2,
      4,
      5
    ],
    "options": [
      "Develop a laboratory bench sheet for recording the test results",
      "Prepare a series of standards",
      "Read the spectrophotometer manufacturer's operation manual",
      "Treat the standard solution and a blank with the colour developing reagent",
      "Use the spectrophotometer to determine the absorbance or transmittance at the specified wavelength"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_35",
    "source": "dsa2",
    "type": "select_all",
    "number": 35,
    "question": "Which items can be used to measure colour in water?",
    "answer": [
      1,
      4,
      5
    ],
    "options": [
      "Colour comparator kits",
      "Colourimeters",
      "Colourimetric meters",
      "Nessler tubes",
      "Spectrophotometers"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_36",
    "source": "dsa2",
    "type": "select_all",
    "number": 36,
    "question": "What do high levels of nitrate in raw water samples indicate?",
    "answer": [
      1,
      3
    ],
    "options": [
      "Biological wastes in the final stage of stabilization",
      "Melted snow water",
      "Runoff from fertilized areas",
      "Water from above the timberline",
      "Water of groundwater origin"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_37",
    "source": "dsa2",
    "type": "select_all",
    "number": 37,
    "question": "Which topics were covered in the 1996 amendments to the SDWA?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Backwash water recycling",
      "Bottled water",
      "Capacity development (technical, financial, managerial)",
      "Consumer awareness",
      "Disinfectants and disinfection by products"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_38",
    "source": "dsa2",
    "type": "select_all",
    "number": 38,
    "question": "Which items are considered microbial contaminants?",
    "answer": [
      1,
      4,
      5
    ],
    "options": [
      "Bacteria",
      "Mercury",
      "Pesticides",
      "Protozoa",
      "Viruses"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_39",
    "source": "dsa2",
    "type": "select_all",
    "number": 39,
    "question": "Before selecting a contaminant for regulation, the EPA must perform which tasks?",
    "answer": [
      1,
      2,
      5
    ],
    "options": [
      "Consult with the scientific community",
      "Demonstrate the contaminant actually occurs in public water systems",
      "Evaluate the best possible treatment processes",
      "Examine the costs of alternative treatment systems",
      "Solicit public comments"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_40",
    "source": "dsa2",
    "type": "select_all",
    "number": 40,
    "question": "Which items are synthetic organic chemicals SOCs?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Food additives",
      "Man-made compounds",
      "Paints",
      "Pesticides",
      "Plastics"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_41",
    "source": "dsa2",
    "type": "select_all",
    "number": 41,
    "question": "Which methods of disinfection are in use today?",
    "answer": [
      1,
      2,
      3,
      5
    ],
    "options": [
      "Application of ozone",
      "Chloramination",
      "Free chlorination",
      "Freezing",
      "Use of chlorine dioxide"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_42",
    "source": "dsa2",
    "type": "select_all",
    "number": 42,
    "question": "The Stage 1 Disinfectants and Disinfection Byproducts rule requires routine monitoring of which regulated contaminants/ disinfectants?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Bromate",
      "Chlorine/ chloramines",
      "Chlorite",
      "DBP precursors",
      "TTHM/ HAA5"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_43",
    "source": "dsa2",
    "type": "select_all",
    "number": 43,
    "question": "Which items are possible public relations objectives?",
    "answer": [
      1,
      2,
      3
    ],
    "options": [
      "Better customer relations",
      "Enhanced organizational credibility",
      "Greater water conservation",
      "Increased O&M budgets",
      "More certified operators"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_44",
    "source": "dsa2",
    "type": "select_all",
    "number": 44,
    "question": "What kinds of information should be in a brochure that supplements a plant tour?",
    "answer": [
      1,
      2,
      3
    ],
    "options": [
      "Accomplishments",
      "Goals",
      "Processes",
      "Regulatory fines",
      "Violations or non compliance issues"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_45",
    "source": "dsa2",
    "type": "select_all",
    "number": 45,
    "question": "Which items are part of the total operating expenses of a water utility?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Administrative",
      "Chemicals",
      "Energy",
      "Salaries",
      "Supplies"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_46",
    "source": "dsa2",
    "type": "select_all",
    "number": 46,
    "question": "Which items are the benefits of an effective operation and maintenance program?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Collecting accurate information and data on which to base the operations and maintenance of the system to justify requests for financial resources",
      "Ensuring the availability of facilities and equipment as intended",
      "Maintaining the reliability of equipment and facilities as designed",
      "Maintaining the value of the investment",
      "Obtaining full use of the system throughout its designed life"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_47",
    "source": "dsa2",
    "type": "select_all",
    "number": 47,
    "question": "Responsibilities in the implementation of cross-connection control programs are shared by which groups?",
    "answer": [
      2,
      3,
      4,
      5
    ],
    "options": [
      "Environmental advocates",
      "Health agencies",
      "Plumbing officials",
      "Water suppliers",
      "Water users/ industry"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_48",
    "source": "dsa2",
    "type": "select_all",
    "number": 48,
    "question": "Which actions should a utility take to increase security and reduce threats from terrorism?",
    "answer": [
      1,
      2,
      4,
      5
    ],
    "options": [
      "Coordinate actions for effective emergency response",
      "Guard against unplanned physical intrusion",
      "Inform media of results of vulnerability assessments",
      "Invest in security and infrastructure improvements",
      "Make security a priority for employees"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_49",
    "source": "dsa2",
    "type": "select_all",
    "number": 49,
    "question": "When determining the emergency limits of a contaminant (amount necessary to cause injury), which factors must be considered?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Attraction of the contaminant to the organism being contaminated",
      "Duration of exposure to the contaminant",
      "Quantity or concentration of the contaminant",
      "Sensitivity of the organism to the contaminant",
      "Solubility of the contaminant in the organism"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_50",
    "source": "dsa2",
    "type": "select_all",
    "number": 50,
    "question": "Which items are the basic elements of a hazard communication program?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Define hazardous conditions",
      "Identify hazardous materials",
      "Obtain chemical information",
      "Properly label hazards",
      "Train operators"
    ],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_1",
    "source": "dsa2",
    "type": "flashcard",
    "number": 1,
    "question": "Why should iron and manganese be controlled in drinking water?",
    "answer": "Clothes washed may become stained, and Fe+Mn promote iron bacteria that form slime in distribution mains. The slime—rust-colored from iron and black from manganese—can slough off during flow changes, causing dirty water along with unpleasant tastes and odors.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_2",
    "source": "dsa2",
    "type": "flashcard",
    "number": 2,
    "question": "What happens when an ion exchange resin becomes fouled with iron rust or insoluble manganese dioxide?",
    "answer": "The resin can be cleaned but this is expensive and the resin capacity is reduced.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_3",
    "source": "dsa2",
    "type": "flashcard",
    "number": 3,
    "question": "How does an operator decide when to backwash a manganese green sand filter?",
    "answer": "Typically when head loss reaches 10PSI or after treating a predetermined number of gallons of water.",
    "options": [],
    "tags": []
  }
];

// For Node.js / module usage
if (typeof module !== "undefined") module.exports = { questions };
