// Water Treatment Study Site — Question Dataset
// Auto-generated by convert.js — do not edit manually
// Source: dsb1.csv
// Generated: 2026-04-30T18:25:57.792Z
// Questions: 91

const questions = [
  {
    "id": "dsb1_factsheet_1",
    "source": "dsb1",
    "type": "factsheet",
    "number": 1,
    "question": "Protozoa- Giardia and Cryptosporidium",
    "answer": "Minimum 3 log removal/ inactivation of cysts/ oocysts",
    "options": [
      "Sources human/ animal feces",
      "Gastrointestinal upset - nausea, vomiting, diarrhoea"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_2",
    "source": "dsb1",
    "type": "factsheet",
    "number": 2,
    "question": "Viruses",
    "answer": "Minimum 4 log removal/ inactivation",
    "options": [
      "Sources human feces",
      "Gastrointestinal upset - nausea, vomiting, diarrhoea",
      "Less common; respiratory, central nervous system, liver, muscular issues",
      "Detected in both surface and ground water sources",
      "Disinfection is a critical barrier"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_3",
    "source": "dsb1",
    "type": "factsheet",
    "number": 3,
    "question": "Escherichia coli | E. coli",
    "answer": "MAC- None/ 100 mL",
    "options": [
      "Sources human/ animal feces",
      "Fecal contamination indicator",
      "Pathogens in human and\r\nanimal feces pose the\r\ngreatest immediate danger\r\nto public health"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_4",
    "source": "dsb1",
    "type": "factsheet",
    "number": 4,
    "question": "Total coliforms",
    "answer": "MAC- None/ 100 mL",
    "options": [
      "Sources human/ animal feces, naturally occuring in soils",
      "Not used as indicators for pathogenic microorganisms - used to determine how the system is operating",
      "Indicate changes in water quality in distribution system"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_5",
    "source": "dsb1",
    "type": "factsheet",
    "number": 5,
    "question": "Turbidity",
    "answer": "Conventional/ Direct <= 0.3 NTU never exceed 1.0 NTU",
    "options": [
      "Slow Sand/ Dia. Earth <= 1.0 NTU never exceed 3.0 NTU",
      "Membrane <= 0.1 NTU investigate higher readings after 15 mins",
      "Inorganic- clays, silts, metal precipitates",
      "Organic- decomposed plant/ animal debris, microorganisms",
      "Particles can hide microorganisms from disinfection, trap heavy metals, etc"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_6",
    "source": "dsb1",
    "type": "factsheet",
    "number": 6,
    "question": "Aluminum",
    "answer": "MAC- 2.9 mg/L",
    "options": [
      "OG- 0.1 mg/L",
      "Natural, coagulant aluminum salts",
      "Neuromuscular effects",
      "It takes treatment\r\nachievability into\r\nconsideration"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-aluminum-in-drinking-water.html"
  },
  {
    "id": "dsb1_factsheet_7",
    "source": "dsb1",
    "type": "factsheet",
    "number": 7,
    "question": "Ammonia",
    "answer": "No MAC or other guidelines",
    "options": [
      "Released from agriculture/ industrial waste, naturally occuring",
      "Added as part of chloramination disinfection strategy",
      "Efficiently metabolized in healthy  people, no adverse effects",
      "To prevent nitrification, limit excess Ammonia in the system to 0.05-0.1 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_8",
    "source": "dsb1",
    "type": "factsheet",
    "number": 8,
    "question": "Arsenic",
    "answer": "0.010 mg/L ALARA",
    "options": [
      "Naturally occuring, mining/ industrial wastes",
      "Cancer (lung,bladder,liver). Neurological effects, numbness",
      "MAC based on treatment achievability"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_9",
    "source": "dsb1",
    "type": "factsheet",
    "number": 9,
    "question": "Barium",
    "answer": "2.0 mg/L",
    "options": [
      "Naturally occuring, industrial spills",
      "Kidney efffects"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-barium-in-drinking-water.html"
  },
  {
    "id": "dsb1_factsheet_10",
    "source": "dsb1",
    "type": "factsheet",
    "number": 10,
    "question": "Bromate",
    "answer": "0.01 mg/L",
    "options": [
      "DBP - ozone disinfection byproduct",
      "Male reproductive effects",
      "Efforts to reduce must not compromise disinfection",
      "Contaminant in hypochlorite solution"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_11",
    "source": "dsb1",
    "type": "factsheet",
    "number": 11,
    "question": "Cadmium",
    "answer": "0.007 mg/L",
    "options": [
      "Leaching from galvanized pipes/ solder. Industrial/ municipal waste",
      "Kidney damage, decreased bone density",
      "Sample similiar to lead, replace piping to minimize exposure"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/publications/healthy-living/water-talk-cadmium-drinking-water.html"
  },
  {
    "id": "dsb1_factsheet_12",
    "source": "dsb1",
    "type": "factsheet",
    "number": 12,
    "question": "Chloramines",
    "answer": "No MAC or other guidelines",
    "options": [
      "Monochloramine is a secondary disinfectant",
      "Formed when chlorine is added in the presence of ammonia",
      "Most Canadian drinking water systems are below 4 mg/L"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-chloramines-drinking-water.html"
  },
  {
    "id": "dsb1_factsheet_13",
    "source": "dsb1",
    "type": "factsheet",
    "number": 13,
    "question": "Chlorate/ Chlorite",
    "answer": "1 mg/L",
    "options": [
      "Chlorine dioxide disinfection byproduct",
      "Thyroid gland effects.  Neurobehavioural effects.",
      "Feed a max dose of 1.2 mg/L of chlorine dioxide"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_14",
    "source": "dsb1",
    "type": "factsheet",
    "number": 14,
    "question": "Chloride",
    "answer": "AO <= 250 mg/L",
    "options": [
      "Natural, salt deposits, sewage, drainage",
      "AO is to minimize complaints based on taste, odour, or excessive scaling"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_15",
    "source": "dsb1",
    "type": "factsheet",
    "number": 15,
    "question": "Chlorine",
    "answer": "No MAC or other guidelines",
    "options": [
      "Used as drinking water disinfectant",
      "Most Canadian systems 0.04 to 2.0 mg/L Free Chlorine"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_16",
    "source": "dsb1",
    "type": "factsheet",
    "number": 16,
    "question": "Chlorine Dioxide",
    "answer": "No MAC or other guidelines",
    "options": [
      "Primary disinfectant",
      "Rapid reduction to chlorite in drinking water systems",
      "Max feed dose of 1.2 mg/L to control chlorite/ chlorate"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_17",
    "source": "dsb1",
    "type": "factsheet",
    "number": 17,
    "question": "Colour",
    "answer": "AO <= 15 TCU",
    "options": [
      "Natural, waste, metals",
      "May interfere with disinfection, removal is for effective treatment"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_18",
    "source": "dsb1",
    "type": "factsheet",
    "number": 18,
    "question": "Copper",
    "answer": "MAC 2 mg/L",
    "options": [
      "AO- 1 mg/L",
      "Natural, copper piping",
      "Gastronintestinal, liver, kidney long term effects",
      "Sample at tap. MAC is for safety, AO is appearance"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/publications/healthy-living/water-talk-copper.html"
  },
  {
    "id": "dsb1_factsheet_19",
    "source": "dsb1",
    "type": "factsheet",
    "number": 19,
    "question": "Cyanide",
    "answer": "MAC 0.2 mg/L",
    "options": [
      "Industrial/ mining, organic compounds",
      "Can be detoxified to a certain extend by humans"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_20",
    "source": "dsb1",
    "type": "factsheet",
    "number": 20,
    "question": "Fluoride",
    "answer": "MAC 1.5 mg/L",
    "options": [
      "Natural, added for dental health",
      "Prevents cavities, high concentrations stain teeth"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_21",
    "source": "dsb1",
    "type": "factsheet",
    "number": 21,
    "question": "Glyphosate",
    "answer": "MAC 0.28 mg/L",
    "options": [
      "Weed control, leaching runoff",
      "Reduced body weight gain",
      "Not expected to migrate to groundwater - lmao!"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_22",
    "source": "dsb1",
    "type": "factsheet",
    "number": 22,
    "question": "Haloacetic Acids (HAAs)",
    "answer": "MAC 0.08 mg/L ALARA",
    "options": [
      "Disinfection byproduct from chlorine",
      "Various organ cancers",
      "MAC based on removing precursors and not compromising system disinfection"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_23",
    "source": "dsb1",
    "type": "factsheet",
    "number": 23,
    "question": "Hardness",
    "answer": "No MAC or other guidelines",
    "options": [
      "Natural, higher in groundwater",
      "Calcium and magnesium are primary makeup, not a health concern.",
      ">200 mg/L is poor, >500 mg/L is unacceptable for domestic use"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_24",
    "source": "dsb1",
    "type": "factsheet",
    "number": 24,
    "question": "Hydrogen Sulphide",
    "answer": "AO <= 0.05 mg/L",
    "options": [
      "Organic breakdown in system from absence of oxygen",
      "AO is for taste/ odour complaints"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_25",
    "source": "dsb1",
    "type": "factsheet",
    "number": 25,
    "question": "Iron",
    "answer": "AO <= 0.1 mg/L",
    "options": [
      "Naturally occuring, mining/ ag",
      "Iron removal reduces manganese, reducing it's health risks"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_26",
    "source": "dsb1",
    "type": "factsheet",
    "number": 26,
    "question": "Lead",
    "answer": "MAC 0.005 mg/L ALARA",
    "options": [
      "Plumbing line leaching",
      "Decreased child IQ. High blood pressure, Anemia (low red blood cell count) in adults",
      "No known safe levels."
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-minimizing-exposure-lead-drinking-water-distribution-systems.html"
  },
  {
    "id": "dsb1_factsheet_27",
    "source": "dsb1",
    "type": "factsheet",
    "number": 27,
    "question": "Magnesium",
    "answer": "No MAC or other guidelines",
    "options": [
      "Naturally occuring",
      "No health effects, contributes to hardness"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_28",
    "source": "dsb1",
    "type": "factsheet",
    "number": 28,
    "question": "Manganese",
    "answer": "MAC 0.12 mg/L",
    "options": [
      "AO <= 0.02 mg/L",
      "Deficits in memory, motor skills",
      "Natural, mining/ landfills. AO is for water staining"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-manganese.html"
  },
  {
    "id": "dsb1_factsheet_29",
    "source": "dsb1",
    "type": "factsheet",
    "number": 29,
    "question": "Mercury",
    "answer": "MAC 0.001 mg/L",
    "options": [
      "Industral, ag effluents",
      "Irreversible neurological issues",
      "Binds to soil, generally not found in drinking water"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_30",
    "source": "dsb1",
    "type": "factsheet",
    "number": 30,
    "question": "Nitrate",
    "answer": "MAC 45 mg/L (10 as nitrate-nitrogen)",
    "options": [
      "Natural, ag/ sewage. Produced from excess ammonia in system",
      "Methaemoglobinaemia , blu ebaby. Throid gland effects. Possibly cancers.",
      "Well water owners should test their supply"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_31",
    "source": "dsb1",
    "type": "factsheet",
    "number": 31,
    "question": "Nitrite",
    "answer": "MAC 3 mg/L (1 mg/L as nitrite-nitrogen)",
    "options": [
      "disinfection byproduct from chlorine or chloramines, industriall/ sewage effluents",
      "Liver cancer"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_32",
    "source": "dsb1",
    "type": "factsheet",
    "number": 32,
    "question": "PFAS",
    "answer": "No MAC. 0.00003 mg/L ALARA",
    "options": [
      "Fire fighting foam, synthetic chemicals",
      "Liver, immune system, kidney, reproduction, etc"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_33",
    "source": "dsb1",
    "type": "factsheet",
    "number": 33,
    "question": "pH",
    "answer": "7.0 to 10.5",
    "options": [
      "Control corrosion strategy"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_34",
    "source": "dsb1",
    "type": "factsheet",
    "number": 34,
    "question": "Selenium",
    "answer": "MAC 0.05 mg/L",
    "options": [
      "Natural, coal plants, mining",
      "Selenosis symptoms, hair loss, tooth decay, nervous system imbalance",
      "Exposure from food, found in non-leaded pipes"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_35",
    "source": "dsb1",
    "type": "factsheet",
    "number": 35,
    "question": "Sodium",
    "answer": "AO <= 200 mg/L",
    "options": [
      "Natural, industrial effluents",
      "Below 20 mg/L if on strict sodium diet",
      "AO based on taste"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_36",
    "source": "dsb1",
    "type": "factsheet",
    "number": 36,
    "question": "Strontium",
    "answer": "MAC 7.0 mg/L",
    "options": [
      "Natural, mining effluents",
      "Bone effects, rickets, child bone development"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/publications/healthy-living/water-talk-strontium.html"
  },
  {
    "id": "dsb1_factsheet_37",
    "source": "dsb1",
    "type": "factsheet",
    "number": 37,
    "question": "Sulphate",
    "answer": "AO <= 500 mg/L",
    "options": [
      "Industrial wastes",
      "High levels can cause diarrhoea or dehydration",
      "AO based on taste and system corrosion"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_38",
    "source": "dsb1",
    "type": "factsheet",
    "number": 38,
    "question": "Sulphide",
    "answer": "AO <= 0.05 mg/L",
    "options": [
      "Sulphate reducing bacteria in distribution system",
      "AO based on taste and odour"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_39",
    "source": "dsb1",
    "type": "factsheet",
    "number": 39,
    "question": "Toluene",
    "answer": "MAC 0.06 mg/L",
    "options": [
      "AO 0.024 mg/L",
      "Petroleum/ chemical industries",
      "Neurological effects, maybe cancer causing",
      "AO based on odour"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_40",
    "source": "dsb1",
    "type": "factsheet",
    "number": 40,
    "question": "Total Dissolved Solids (TDS)",
    "answer": "AO <= 500 mg/L",
    "options": [
      "Natural, wastewaters",
      "High TDS, excessive scaling",
      "Ca, Mg, Na, K, carbonates, etc"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_41",
    "source": "dsb1",
    "type": "factsheet",
    "number": 41,
    "question": "Trihalomethanes (THMs)",
    "answer": "MAC 0.1 mg/L",
    "options": [
      "Chlorine disinfectant byproduct",
      "Liver effects, possibly cancer causing"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_42",
    "source": "dsb1",
    "type": "factsheet",
    "number": 42,
    "question": "Uranium",
    "answer": "MAC 0.02 mg/L",
    "options": [
      "Natural, nuclear industry waste",
      "Kidney",
      "Challenges with private wells"
    ],
    "tags": [],
    "note": "https-//www.canada.ca/en/health-canada/services/environmental-workplace-health/reports-publications/water-quality/water-talk-uranium-drinking-water-2010-health-canada-brochure.html"
  },
  {
    "id": "dsb1_factsheet_43",
    "source": "dsb1",
    "type": "factsheet",
    "number": 43,
    "question": "Vinyl Chloride",
    "answer": "MAC 0.002 mg/L ALARA",
    "options": [
      "Industrial effluent, leach from polyvinyl chloride pipes (PVC)",
      "Liver cancer, Raynaud's disease",
      "PVC pipe not expected significant"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_44",
    "source": "dsb1",
    "type": "factsheet",
    "number": 44,
    "question": "Xylenes",
    "answer": "MAC 0.09 mg/L",
    "options": [
      "AO 0.02 mg/L",
      "Petro/ chemical industries",
      "Neuromuscular effects",
      "AO based on odour"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_45",
    "source": "dsb1",
    "type": "factsheet",
    "number": 45,
    "question": "Zinc",
    "answer": "AO <= 5 mg/L",
    "options": [
      "Natural, galvanized pipes",
      "AO based on taste and odour"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_1",
    "source": "dsb1",
    "type": "best_answer",
    "number": 1,
    "question": "According to the Summary GCDWQ 2025, what is the MAC for Haloacetic acids (HAAs)?",
    "answer": 3,
    "options": [
      "<= 0.01 mg/L",
      "<= 0.04 mg/L",
      "<= 0.08 mg/L",
      "<= 1.0 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_2",
    "source": "dsb1",
    "type": "best_answer",
    "number": 2,
    "question": "According to the Summary GCDWQ 2025, NTU values greater than _______ for 15 minutes should be immediately investigated?",
    "answer": 1,
    "options": [
      "<= 0.01 NTU",
      "<= 0.03 NTU",
      "<= 1.0 NTU",
      "<= 3.0 NTU"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_3",
    "source": "dsb1",
    "type": "best_answer",
    "number": 3,
    "question": "According to the Summary GCDWQ 2025, what is the AO for Total Dissolved Solids (TDS)?",
    "answer": 4,
    "options": [
      "<= 1 mg/L",
      "<= 45 mg/L",
      "<= 250 mg/L",
      "<= 500 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_4",
    "source": "dsb1",
    "type": "best_answer",
    "number": 4,
    "question": "What is the primary issue or concern with excessive TDs concentrations in drinking water?",
    "answer": 4,
    "options": [
      "Suspected carcinogen",
      "The kidney stones",
      "Severe nausea and vomiting",
      "Objectionable taste and corrosivity"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_5",
    "source": "dsb1",
    "type": "best_answer",
    "number": 5,
    "question": "According to the Summary GCDWQ 2025, which of the following parameters have both a MAC and an AO standard?",
    "answer": 2,
    "options": [
      "Iron",
      "Manganese",
      "Turbidity",
      "All of the above"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_6",
    "source": "dsb1",
    "type": "best_answer",
    "number": 6,
    "question": "Trihalomethanes (THMs) are produced when-",
    "answer": 1,
    "options": [
      "Free chlorine reacts with bromide and other natural organic matter",
      "VOCs react with free chlorine",
      "Naturally occurring inorganic matter reacts with chlorine residuals",
      "Total chlorine reacts with haloacetic acids"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_7",
    "source": "dsb1",
    "type": "best_answer",
    "number": 7,
    "question": "According to the Summary GCDWQ 2025, any method of THM control must not-",
    "answer": 3,
    "options": [
      "Change the physical appearance of water",
      "Change the taste of water",
      "Compromise the effectiveness of water disinfection",
      "Change the apparent or true colour of the water"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_8",
    "source": "dsb1",
    "type": "best_answer",
    "number": 8,
    "question": "According to the Summary GCDWQ 2025, the NTU's for Diatomaceous earth (DE)/ slow sand filtration shall be ______ 95% of the time and shall not exceed ______.",
    "answer": 3,
    "options": [
      "<= 0.1 NTU and <= 0.3 NTU",
      "<= 0.3 NTU and <=1.0 NTU",
      "<= 1.0 NTU and <= 3.0 NTU",
      "<= 3.0 NTU and <= 5.0 NTU"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_9",
    "source": "dsb1",
    "type": "best_answer",
    "number": 9,
    "question": "What is the Mac for arsenic (As)?",
    "answer": 2,
    "options": [
      "0/ 100 mL",
      "0.01 mg/L",
      "0.05 mg/L",
      "1.0 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_10",
    "source": "dsb1",
    "type": "best_answer",
    "number": 10,
    "question": "What is the MAC for manganese(Mn)?",
    "answer": 1,
    "options": [
      "<= 0.06 mg/L",
      "<= 0.1 mg/L",
      "<= 0.12 mg/L",
      "<= 0.15 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_11",
    "source": "dsb1",
    "type": "best_answer",
    "number": 11,
    "question": "The Summary GCDWQ 2025 specifies an AO of 7.0 to 10.5 pH for what reason?",
    "answer": 2,
    "options": [
      "Taste problems",
      "Corrosion or scaling problems",
      "Increased biofilm formation",
      "Lower dissolved oxygen levels"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_12",
    "source": "dsb1",
    "type": "best_answer",
    "number": 12,
    "question": "According to the Summary GCDWQ 2025, what is the MAC for fluoride?",
    "answer": 3,
    "options": [
      "<= 0.8 mg/L",
      "<= 1.0 mg/L",
      "<= 1.5 mg/L",
      "<= 2.0 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_13",
    "source": "dsb1",
    "type": "best_answer",
    "number": 13,
    "question": "According to the Summary GCDWQ 2025, the MAC for nitrates is <= 45 mg/L, expressed as nitrate-nitrogen it's-",
    "answer": 3,
    "options": [
      "<= 1.0 mg/L",
      "<= 5.0mg/L",
      "<= 10 mg/L",
      "<= 45 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_14",
    "source": "dsb1",
    "type": "best_answer",
    "number": 14,
    "question": "TCU stands for true colour units, what is true colour?",
    "answer": 2,
    "options": [
      "The colour in a sample before it is filtered",
      "The colour in a sample after it is filtered",
      "The colour in a sample before it is disinfected",
      "The colour in the sample after it is disinfected"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_15",
    "source": "dsb1",
    "type": "best_answer",
    "number": 15,
    "question": "According to the Summary GCDWQ 2025, what is the treatment goal for protozoa?",
    "answer": 2,
    "options": [
      "Minimum 2 log reduction",
      "Minimum 3 log reduction",
      "Minimum 4 log reduction",
      "Minimum 5 log reduction"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_16",
    "source": "dsb1",
    "type": "best_answer",
    "number": 16,
    "question": "According to the Summary GCDWQ 2025, what is the treatment goal for viruses?",
    "answer": 3,
    "options": [
      "Minimum 2 log reduction",
      "Minimum 3 log reduction",
      "Minimum 4 log reduction",
      "Minimum 5 log reduction"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_17",
    "source": "dsb1",
    "type": "best_answer",
    "number": 17,
    "question": "According to the Summary GCDWQ 2025, what is the AO for sulphates?",
    "answer": 4,
    "options": [
      "<= 10 mg/L",
      "<= 25 mg/L",
      "<= 250 mg/L",
      "<= 500 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_18",
    "source": "dsb1",
    "type": "best_answer",
    "number": 18,
    "question": "What is the issue or problem with excessive sulphate levels?",
    "answer": 3,
    "options": [
      "Yellowish colour to the water",
      "Brought an egg odour",
      "Laxative effect",
      "Sulfuric acid causing pH issues"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_19",
    "source": "dsb1",
    "type": "best_answer",
    "number": 19,
    "question": "According to the Summary GCDWQ 2025, what is the AO for chloride?",
    "answer": 3,
    "options": [
      "<= 10 mg/L",
      "<= 25 mg/L",
      "<= 250 mg/L",
      "<= 500 mg/L"
    ],
    "tags": []
  },
  {
    "id": "dsb1_best_answer_20",
    "source": "dsb1",
    "type": "best_answer",
    "number": 20,
    "question": "According to the Summary GCDWQ 2025, water with a hardness great than _____ is poor, and greater than ______ is unacceptable for domestic use.",
    "answer": 3,
    "options": [
      "150 mg/L poor, 300 mg/L unacceptable",
      "200 mg/L poor, 400 mg/L unacceptable",
      "200 mg/L poor, 500 mg/L unacceptable",
      "300 mg/L poor, 500 mg/L unacceptable"
    ],
    "tags": []
  },
  {
    "id": "dsb1_true_false_1",
    "source": "dsb1",
    "type": "true_false",
    "number": 1,
    "question": "Iron has an aesthetic objective of ≤ 0.3 mg/L due to staining and taste issues.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The AO is <= 0.1 mg/L as of 2025 Canadian guidelines"
  },
  {
    "id": "dsb1_true_false_2",
    "source": "dsb1",
    "type": "true_false",
    "number": 2,
    "question": "True colour has an aesthetic objective (AO) of <= 15 TCU.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_3",
    "source": "dsb1",
    "type": "true_false",
    "number": 3,
    "question": "Turbidity has an aesthetic objective (AO) of ≤ 1.0 NTU with conventional filtration.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's an operational guideline, not an AO and the target is <= 0.3 NTU"
  },
  {
    "id": "dsb1_true_false_4",
    "source": "dsb1",
    "type": "true_false",
    "number": 4,
    "question": "Chloride has an aesthetic objective of ≤ 250 mg/L due to taste, odour, scaling.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_5",
    "source": "dsb1",
    "type": "true_false",
    "number": 5,
    "question": "pH has an aesthetic objective range of 6.5–8.5.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Canadian guidelines are 7.0 to 10.5 pH"
  },
  {
    "id": "dsb1_true_false_6",
    "source": "dsb1",
    "type": "true_false",
    "number": 6,
    "question": "Zinc has an aesthetic objective <= 5.0 mg/L because of toxicity concerns.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "AO is for taste/ appearance, not toxicity"
  },
  {
    "id": "dsb1_true_false_7",
    "source": "dsb1",
    "type": "true_false",
    "number": 7,
    "question": "Sodium has an aesthetic objective of ≤ 200 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_8",
    "source": "dsb1",
    "type": "true_false",
    "number": 8,
    "question": "The MAC for lead is ≤ 0.005 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_9",
    "source": "dsb1",
    "type": "true_false",
    "number": 9,
    "question": "The MAC for fluoride is ≤ 1.5 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_10",
    "source": "dsb1",
    "type": "true_false",
    "number": 10,
    "question": "The MAC for arsenic is ≤ 0.025 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.01 mg/L ALARA"
  },
  {
    "id": "dsb1_true_false_11",
    "source": "dsb1",
    "type": "true_false",
    "number": 11,
    "question": "The MAC for total trihalomethanes (TTHMs) is ≤ 0.10 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_12",
    "source": "dsb1",
    "type": "true_false",
    "number": 12,
    "question": "The MAC for total haloacetic acids (HAAs) is ≤ 0.10 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.08 mg/L ALARA"
  },
  {
    "id": "dsb1_true_false_13",
    "source": "dsb1",
    "type": "true_false",
    "number": 13,
    "question": "The MAC for nitrate and nitrite are 45 mg/L and 1 mg/L, respectively",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 3 mg/L as nitrite (1 as nitrite-nitrogen)"
  },
  {
    "id": "dsb1_true_false_14",
    "source": "dsb1",
    "type": "true_false",
    "number": 14,
    "question": "The MAC for total microcystins is ≤ 0.0015 mg/L",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_15",
    "source": "dsb1",
    "type": "true_false",
    "number": 15,
    "question": "The MAC for benzene is ≤ 0.005 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_16",
    "source": "dsb1",
    "type": "true_false",
    "number": 16,
    "question": "The MAC for mercury is ≤ 0.01 mg/L",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.001 mg/L"
  },
  {
    "id": "dsb1_true_false_17",
    "source": "dsb1",
    "type": "true_false",
    "number": 17,
    "question": "The MAC for manganese is ≤ 0.12 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_18",
    "source": "dsb1",
    "type": "true_false",
    "number": 18,
    "question": "The aesthetic objective for manganese is ≤ 0.01 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's <= 0.02 mg/L"
  },
  {
    "id": "dsb1_true_false_19",
    "source": "dsb1",
    "type": "true_false",
    "number": 19,
    "question": "The MAC for antimony is ≤ 0.006 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_20",
    "source": "dsb1",
    "type": "true_false",
    "number": 20,
    "question": "The MAC for chlorate is ≤ 1.0 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_21",
    "source": "dsb1",
    "type": "true_false",
    "number": 21,
    "question": "The MAC for N-Nitrosodimethylamine (NDMA) is ≤ 0.004 mg/L",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.00004 mg/L"
  },
  {
    "id": "dsb1_true_false_22",
    "source": "dsb1",
    "type": "true_false",
    "number": 22,
    "question": "The MAC for strontium is ≤ 7.0 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_22",
    "source": "dsb1",
    "type": "true_false",
    "number": 22,
    "question": "The MAC for tetrachloroethylene (PCE) is ≤ 0.01 mg/L.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_true_false_23",
    "source": "dsb1",
    "type": "true_false",
    "number": 23,
    "question": "The MAC for trichloroethylene (TCE) is ≤ 0.05 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.005 mg/L"
  },
  {
    "id": "dsb1_true_false_24",
    "source": "dsb1",
    "type": "true_false",
    "number": 24,
    "question": "The MAC for lead is ≤ 0.05 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.005 mg/L ALARA"
  },
  {
    "id": "dsb1_true_false_25",
    "source": "dsb1",
    "type": "true_false",
    "number": 25,
    "question": "The MAC for benzene is ≤ 0.5 mg/L.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "It's 0.005 mg/L"
  }
];

// For Node.js / module usage
if (typeof module !== "undefined") module.exports = { questions };
