// Water Treatment Study Site — Question Dataset
// Auto-generated by convert.js — do not edit manually
// Source: sample2.csv
// Generated: 2026-04-22T00:35:16.979Z
// Questions: 55

const questions = [
  {
    "id": "sii_true_false_1",
    "source": "sii",
    "type": "true_false",
    "number": 1,
    "question": "Both iron and manganese are essential to the growth of many plants and animals, including humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_9",
    "source": "sii",
    "type": "true_false",
    "number": 9,
    "question": "The feed rates determined by jar tests always produce the exact same results in the actual plant.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_11",
    "source": "sii",
    "type": "true_false",
    "number": 11,
    "question": "The overwhelming bulk of THM precursors in water are from industrial organic chemicals.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_12",
    "source": "sii",
    "type": "true_false",
    "number": 12,
    "question": "When collecting water samples for THM analysis, be sure to collect the sample before the water temperature becomes constant.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_14",
    "source": "sii",
    "type": "true_false",
    "number": 14,
    "question": "Low levels of arsenic consumed over a long period of time can cause cancer and non cancerous toxic effects on humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_16",
    "source": "sii",
    "type": "true_false",
    "number": 16,
    "question": "All waters contain various amounts of total dissolved solids (TDS), including fresh water.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_18",
    "source": "sii",
    "type": "true_false",
    "number": 18,
    "question": "The output of a positive displacement pump may be throttled.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_20",
    "source": "sii",
    "type": "true_false",
    "number": 20,
    "question": "Trash and grit may be disposed of in landfills.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_24",
    "source": "sii",
    "type": "true_false",
    "number": 24,
    "question": "Operators must be familiar with equipment and understand what it is intended to do before developing a preventative maintenance program and maintaining equipment.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_28",
    "source": "sii",
    "type": "true_false",
    "number": 28,
    "question": "Never pour water on a chlorine leak because this will only create a bigger problem by enlarging the leak.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_32",
    "source": "sii",
    "type": "true_false",
    "number": 32,
    "question": "Pneumatic instrumentation depends upon a constant source of clean, dry, pressurized air for reliable operation.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_33",
    "source": "sii",
    "type": "true_false",
    "number": 33,
    "question": "The fumes from hydrofluorosilicic acid (H2SiF6) can corrode metal and etch glass on protective equipment.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_34",
    "source": "sii",
    "type": "true_false",
    "number": 34,
    "question": "In reactions with most metals, hydrochloric acid will produce hydrogen gas.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_35",
    "source": "sii",
    "type": "true_false",
    "number": 35,
    "question": "Anhydrous ammonia (gas) may be stored in the same room with chlorine (gas).",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_40",
    "source": "sii",
    "type": "true_false",
    "number": 40,
    "question": "Chloroform is the most common THM found in drinking water.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_42",
    "source": "sii",
    "type": "true_false",
    "number": 42,
    "question": "MCLs apply whether the contaminant is from naturally occurring sources or from man-made pollution.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_44",
    "source": "sii",
    "type": "true_false",
    "number": 44,
    "question": "The presence of coliform bacteria indicates that other harmful organisms may be present in the water.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_45",
    "source": "sii",
    "type": "true_false",
    "number": 45,
    "question": "Tier 1 violations are any situations in which even a brief violation or short term exposure to a contaminant has the potential to cause serious negative effect on human health.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_46",
    "source": "sii",
    "type": "true_false",
    "number": 46,
    "question": "No discipline problem ever solves itself, and the sooner you deal with the problem, the better will be the outcome.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_47",
    "source": "sii",
    "type": "true_false",
    "number": 47,
    "question": "Written communication is less demanding than oral communication and requires less careful preparation.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_48",
    "source": "sii",
    "type": "true_false",
    "number": 48,
    "question": "Customer calls are frequently your first indication that something may be wrong.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_49",
    "source": "sii",
    "type": "true_false",
    "number": 49,
    "question": "Corrective maintenance, including emergency maintenance, is considered reactive maintenance.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_50",
    "source": "sii",
    "type": "true_false",
    "number": 50,
    "question": "The SCADA system allows operators to enhance the efficiency of their water facility by keeping them fully informed and fully in control.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_true_false_52",
    "source": "sii",
    "type": "true_false",
    "number": 52,
    "question": "On-the-Job-Training (OJT) is a good way of preventing accidents with an inexperienced operator.",
    "answer": "FALSE",
    "options": [],
    "tags": []
  },
  {
    "id": "sii_multi_choice_1",
    "source": "sii",
    "type": "multi_choice",
    "number": 1,
    "question": "How can the growth of iron bacteria be controlled by caustic soda?",
    "answer": "Chlorination",
    "options": [
      "Caustic Soda",
      "Chlorination",
      "Permanganate",
      "Sulfuric Acid"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_3",
    "source": "sii",
    "type": "multi_choice",
    "number": 3,
    "question": "What should an operator do when operating an ion exchange unit and iron & manganese start to appear in the treated water?",
    "answer": "Regenerate with a brine solution",
    "options": [
      "Inform consumers of the presence of iron and manganese",
      "Keep the unit operating until breakthrough becomes excessive",
      "Notify the regulatory agency or the health department",
      "Regenerate with a brine solution"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_4",
    "source": "sii",
    "type": "multi_choice",
    "number": 4,
    "question": "What happens if children drink a recommended dose of fluoride?",
    "answer": "Fewer dental cavities",
    "options": [
      "Bones become stronger",
      "Growth will be stunted",
      "Fewer dental cavities",
      "Perform better in school"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_5",
    "source": "sii",
    "type": "multi_choice",
    "number": 5,
    "question": "When working with fluoridation systems using a sodium fluoride solution, why is the hardness of the water very important?",
    "answer": "Scaling can be caused by hardness",
    "options": [
      "Corrosion can be caused by hardness",
      "Pump cavitation is a problem when hardness is present",
      "Scaling can be caused by hardness",
      "Water hammer problems are caused by hardness"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_6",
    "source": "sii",
    "type": "multi_choice",
    "number": 6,
    "question": "Water hardness is a measure of which item?",
    "answer": "Soap or detergent-consuming power of water.",
    "options": [
      "Corrosivity of water",
      "Density of water",
      "Penetration power of water",
      "Soap or detergent-consuming power of water"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_7",
    "source": "sii",
    "type": "multi_choice",
    "number": 7,
    "question": "Why should bagged quicklime never be stored close to combustible materials?",
    "answer": "Considerable heat will be generated if the lime gets wet",
    "options": [
      "Combustible materials can use lime for fuel when burning",
      "Considerable heat will be generated if the lime gets wet",
      "Heat from a fire could melt the lime",
      "Lime easily catches on fire"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_8",
    "source": "sii",
    "type": "multi_choice",
    "number": 8,
    "question": "How can an operator prevent scale formation on the filter sand, distribution mains, and household plumbing?",
    "answer": "Converting the excess caustic & unprecipitated carbonate ions to soluble forms",
    "options": [
      "Converting the excess caustic & unprecipitated carbonate ions to soluble forms",
      "implementing a flushing program",
      "Maintaining high water velocities throughout the system",
      "Regular backwashing"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_13",
    "source": "sii",
    "type": "multi_choice",
    "number": 13,
    "question": "What is the most common pretreatment process to remove turbidity and suspended solids?",
    "answer": "Filtration",
    "options": [
      "Chlorination",
      "Coagulation. Flocculation",
      "Filtration",
      "Sedimentation"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_14",
    "source": "sii",
    "type": "multi_choice",
    "number": 14,
    "question": "What can be applied to inhibit the growth of bacterial slimes and molds on membrane surfaces?",
    "answer": "Chlorine",
    "options": [
      "Acetone",
      "Chlorine",
      "Soda ash",
      "Sulfuric acid"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_15",
    "source": "sii",
    "type": "multi_choice",
    "number": 15,
    "question": "For electrodialysis demineralization, acid addition is part of the pretreatment of the feed water supply to prevent what?",
    "answer": "Carbonate scaling",
    "options": [
      "Carbonate scaling",
      "Membrane compaction",
      "Membrane corrosion",
      "Polarization"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_16",
    "source": "sii",
    "type": "multi_choice",
    "number": 16,
    "question": "What regular activity is the key to speedy sludge drying in a sludge drying bed",
    "answer": "Application of a thin layer of sludge",
    "options": [
      "Application of a thick layer of sludge",
      "Application of a thin layer of sludge",
      "Removal of the dried portion of sludge",
      "Removal of the water on top of the sludge"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_18",
    "source": "sii",
    "type": "multi_choice",
    "number": 18,
    "question": "What is an ampere?",
    "answer": "Unit of electric current or an indication of how hard the electricity is working",
    "options": [
      "Electrical pressure available to cause a flow of current when an circuit is closed",
      "Level of shock provided by a circuit",
      "Measure of the number of phases provided by the current",
      "Unit of electric current or an indication of how hard the electricity is working"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_19",
    "source": "sii",
    "type": "multi_choice",
    "number": 19,
    "question": "How can an operator determine if a circuit breaker has been tripped?",
    "answer": "Breaker handle will be at the midpoint",
    "options": [
      "Breaker handle will be at the midpoint",
      "Lockout/ tagout device is secure",
      "Overload relay is overheated",
      "Strip or wire off fusible metal is melted"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_20",
    "source": "sii",
    "type": "multi_choice",
    "number": 20,
    "question": "Why should bearing grease be purchased in cartridge form?",
    "answer": "Minimize the chance of getting dirt into the lubricant",
    "options": [
      "Facilitate applying grease",
      "Minimize the chance of getting dirt into the lubricant",
      "Optimize grease storage space",
      "Reduce costs of the purchasing grease"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_21",
    "source": "sii",
    "type": "multi_choice",
    "number": 21,
    "question": "How can an operator determine if a pump is primed?",
    "answer": "Pump must be completely filled with water",
    "options": [
      "Pump is in a good shape",
      "Pump is ready to start",
      "Pump must be completely filled with water",
      "Pump must be properly aligned"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_23",
    "source": "sii",
    "type": "multi_choice",
    "number": 23,
    "question": "The purpose of cathodic protection is to prevent what?",
    "answer": "Breasting of base metal surfaces",
    "options": [
      "Operators from being exposed to toxic gases",
      "Formation of slimes on walkways",
      "Rusting of base metal surfaces",
      "Scaling and deposition of chemicals on metal surfaces"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_25",
    "source": "sii",
    "type": "multi_choice",
    "number": 25,
    "question": "What is a very precise method of measuring fluctuating water levels?",
    "answer": "Bubbler tube",
    "options": [
      "Bubbler tube",
      "Displacer",
      "Electrical probe",
      "Pump pressure gauge"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_26",
    "source": "sii",
    "type": "multi_choice",
    "number": 26,
    "question": "What is the \"test\" button on an annunciator panel used for?",
    "answer": "Confirm that no alarm lamps have been burned out",
    "options": [
      "Confirm that no alarm lamps have been burned out",
      "Initiate an alarm condition at each alarm site",
      "Perform alarm drills throughout the plant",
      "Verify the noise level of each alarm"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_27",
    "source": "sii",
    "type": "multi_choice",
    "number": 27,
    "question": "What is the most useful piece of general electrical test equipment?",
    "answer": "Multimeter tester",
    "options": [
      "Battery charger tester",
      "Ground fault tester",
      "Live circuit tester",
      "Multimeter tester"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_28",
    "source": "sii",
    "type": "multi_choice",
    "number": 28,
    "question": "How can bases be neutralized?",
    "answer": "Strong acids",
    "options": [
      "Ammonia",
      "Deionized water",
      "Dilute acids",
      "Strong acids"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_29",
    "source": "sii",
    "type": "multi_choice",
    "number": 29,
    "question": "Carbon dioxide gas is considered dangerous and can cause what?",
    "answer": "Suffocation due to the lack of oxygen",
    "options": [
      "Acidic types of skin burns",
      "Cancer",
      "Injury to the eyes",
      "Suffocation due to the lack of oxygen"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_30",
    "source": "sii",
    "type": "multi_choice",
    "number": 30,
    "question": "Why are high levels of oxygen above 22.5% dangerous?",
    "answer": "Increase the possibility of an explosion",
    "options": [
      "Cause excessive exertion by operators",
      "Confuse an operator's thinking ability",
      "Increase the possibility of an explosion",
      "Mask the odor of toxic gases"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_31",
    "source": "sii",
    "type": "multi_choice",
    "number": 31,
    "question": "What type of electric shock protection must be used when operating power tools outdoors?",
    "answer": "Ground fault circuit interrupter GFCI",
    "options": [
      "Ground fault circuit interrupter GFCI",
      "Insulated screwdrivers",
      "Lockout/ tagout",
      "Rubber gloves"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_32",
    "source": "sii",
    "type": "multi_choice",
    "number": 32,
    "question": "The purpose of a spectrometer calibration curve is to determine \"if the\" what?",
    "answer": "Spectrometer needs recalibration",
    "options": [
      "Sample has succeeded its holding time",
      "Spectrometer needs recalibration",
      "Spectrometer reagents are deteriorating",
      "Concentration of the water quality indicator contained in a sample"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_33",
    "source": "sii",
    "type": "multi_choice",
    "number": 33,
    "question": "What causes apparent color in water?",
    "answer": "Dissolved organic substances or certain minerals",
    "options": [
      "Dissolved organic substances or certain minerals",
      "Hardness ions",
      "Iron and manganese",
      "Suspended materials (colloidal substances)"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_34",
    "source": "sii",
    "type": "multi_choice",
    "number": 34,
    "question": "Specific conductance or conductivity is a numerical expression of which term?",
    "answer": "Ability of water to conduct an electric current",
    "options": [
      "Ability of water to conduct an electric current",
      "Ease of which an electric current heats the water sample",
      "Number of total dissolved solids in a water sample",
      "Transmissibility of a sample of water in a pipeline"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_38",
    "source": "sii",
    "type": "multi_choice",
    "number": 38,
    "question": "What is the important difference between MCL and MCLG?",
    "answer": "MCLG is non enforceable and MCL is enforceable standard",
    "options": [
      "MCLG is always established before the MCL",
      "MCLG is nonenforceable and MCL is an enforceable standard",
      "MCLG is preferred by regulatory agencies in lieu of the MCL",
      "MCL is always lower than the MCLG"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_39",
    "source": "sii",
    "type": "multi_choice",
    "number": 39,
    "question": "What causes backflow situations in distribution systems?",
    "answer": "Either back pressure or back siphonage",
    "options": [
      "Defective clearwell safety valves",
      "Either back pressure or back siphonage",
      "Failure of the filter backwash system",
      "Malfunctioning distribution system sampling stations"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_40",
    "source": "sii",
    "type": "multi_choice",
    "number": 40,
    "question": "What is the National Terrorism Advisory System?",
    "answer": "System used to issue informal, detailed alerts about specific or credible terrorist threats",
    "options": [
      "Group with instructions to broadcast warnings of terrorist activity-",
      "Network of agents throughout the world that monitor the potential for terrorist activity",
      "System used to issue informal, detailed alerts about specific or credible terrorist threats",
      "Terrorist detection system programmed to alert water utility agencies"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_41",
    "source": "sii",
    "type": "multi_choice",
    "number": 41,
    "question": "What is an acute toxic agent?",
    "answer": "Causes injury quickly",
    "options": [
      "Bioaccumulates in the system of a susceptible individual",
      "Causes injury quickly",
      "Causes injury to occur over an extended period of exposure",
      "Ingested by an individual"
    ],
    "tags": []
  },
  {
    "id": "sii_multi_choice_43",
    "source": "sii",
    "type": "multi_choice",
    "number": 43,
    "question": "What is the purpose of the Safety Data Sheet (SDS)?",
    "answer": "Readily available reference document that includes complete information on the hazardous substance",
    "options": [
      "Readily available reference document that includes complete information on the hazardous substance",
      "Protect operators from overexposure to hazardous atmospheres",
      "Protect operators from exposure to hazardous substances",
      "Require manufacturers to submit safety information upon delivery of a hazardous substance"
    ],
    "tags": []
  }
];

// For Node.js / module usage
if (typeof module !== "undefined") module.exports = { questions };
