// Water Treatment Study Site — Question Dataset
// Auto-generated by convert.js — do not edit manually
// Source: sample.csv
// Generated: 2026-04-27T10:04:24.726Z
// Questions: 40

const questions = [
  {
    "id": "dsa1_true_false_18",
    "source": "dsa1",
    "type": "true_false",
    "number": 18,
    "question": "Use regular pipe fittings when making connections with chlorine containers.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Do not use regular pipe fittings when making connections with containers"
  },
  {
    "id": "dsa1_true_false_22",
    "source": "dsa1",
    "type": "true_false",
    "number": 22,
    "question": "Water containing high levels of hardness tend to be more aggressive.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "Water containing very little hardness tends to be more aggressive"
  },
  {
    "id": "dsa1_true_false_23",
    "source": "dsa1",
    "type": "true_false",
    "number": 23,
    "question": "Increase nutrient levels in source water may result from either natural conditions or from human activity within the watershed.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_true_false_26",
    "source": "dsa1",
    "type": "true_false",
    "number": 26,
    "question": "Ideally process control measurements should be made on a continuous basis by special instrumentation.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_2",
    "source": "dsa1",
    "type": "best_answer",
    "number": 2,
    "question": "What is the cause of stratification in lakes and reservoirs?",
    "answer": 2,
    "options": [
      "Breezes starting the circulation of surface water",
      "Formation of separate layers of temperature, plant life, or animal life",
      "Lake turn over",
      "Uniform water temperature profile in a lake or reservoir"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_5",
    "source": "dsa1",
    "type": "best_answer",
    "number": 5,
    "question": "What is the best tool for managing watersheds?",
    "answer": 3,
    "options": [
      "Political process",
      "Public hearings",
      "Regulatory process",
      "Voluntary compliance"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_16",
    "source": "dsa1",
    "type": "best_answer",
    "number": 16,
    "question": "Why should a filter be drained if it is going to be out of service for a prolonged.?",
    "answer": 2,
    "options": [
      "To allow the media to dry out",
      "To avoid algal growth",
      "To prevent filter tank from floating on groundwater",
      "To save water"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_23",
    "source": "dsa1",
    "type": "best_answer",
    "number": 23,
    "question": "Where are the monitoring samples for the Lead and Copper Rule collected?",
    "answer": 1,
    "options": [
      "At the consumers tab",
      "At the entrance to the clairwell",
      "At the most distant locations in the distribution system",
      "At the raw water source"
    ],
    "tags": []
  },
  {
    "id": "dsa1_best_answer_29",
    "source": "dsa1",
    "type": "best_answer",
    "number": 29,
    "question": "What should an operator do first when a treatment process upset results in the failure to meet a specific drinking water quality standard?",
    "answer": 2,
    "options": [
      "Fix process upset",
      "Notify appropriate local health authorities",
      "Stop operating process",
      "Switch sources of raw water"
    ],
    "tags": []
  },
  {
    "id": "dsa2_true_false_7",
    "source": "dsa2",
    "type": "true_false",
    "number": 7,
    "question": "The stability of treated water is determined by measuring the pH and calculating the Langley index.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_9",
    "source": "dsa2",
    "type": "true_false",
    "number": 9,
    "question": "The feed rates determined by jar tests always produce the exact same results in the actual plant.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The feed rates determined by jar tests do not always produce the exact same results as the actual plant"
  },
  {
    "id": "dsa2_true_false_13",
    "source": "dsa2",
    "type": "true_false",
    "number": 13,
    "question": "The higher the pH of water, the slower the production of THMs.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The higher the pH of the water the faster the production of THMS"
  },
  {
    "id": "dsa2_true_false_14",
    "source": "dsa2",
    "type": "true_false",
    "number": 14,
    "question": "Low levels of arsenic consumed over a long period of time can cause cancer and non cancerous toxic effects on humans.",
    "answer": "TRUE",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_true_false_17",
    "source": "dsa2",
    "type": "true_false",
    "number": 17,
    "question": "The rate of hydrolysis is accelerated by decreased temperature.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The rate of hydrolysis is accelerated by increased temperature"
  },
  {
    "id": "dsa2_true_false_18",
    "source": "dsa2",
    "type": "true_false",
    "number": 18,
    "question": "The output of a positive displacement pump may be throttled.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "The output of a positive displacement pump may not be throttled"
  },
  {
    "id": "dsa2_true_false_30",
    "source": "dsa2",
    "type": "true_false",
    "number": 30,
    "question": "Long detection lags can result in stable processes and good control.",
    "answer": "FALSE",
    "options": [],
    "tags": [],
    "context": "long detection legs can result in unstable processes and poor control"
  },
  {
    "id": "dsa2_best_answer_5",
    "source": "dsa2",
    "type": "best_answer",
    "number": 5,
    "question": "When working with fluoridation systems using a sodium fluoride solution, why is the hardness of the water very important?",
    "answer": 3,
    "options": [
      "Corrosion can be caused by hardness",
      "Pump cavitation is a problem when hardness is present",
      "Scaling can be caused by hardness",
      "Water hammer problems are caused by hardness"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_11",
    "source": "dsa2",
    "type": "best_answer",
    "number": 11,
    "question": "What is a major advantage of removing precursors before chlorine is added?",
    "answer": 1,
    "options": [
      "Allows the continued use of free chlorine as a disinfectant",
      "Facilitates the ultimate disposal of the precursors",
      "Option preferred by most water consumers",
      "Promotes the use of chloramination."
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_21",
    "source": "dsa2",
    "type": "best_answer",
    "number": 21,
    "question": "How can an operator determine if a pump is primed?",
    "answer": 3,
    "options": [
      "Pump is in a good shape",
      "Pump is ready to start",
      "Pump must be completely filled with water",
      "Pump must be properly aligned"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_33",
    "source": "dsa2",
    "type": "best_answer",
    "number": 33,
    "question": "What causes apparent colour in water?",
    "answer": 4,
    "options": [
      "Dissolved organic substances or certain minerals",
      "Hardness ions",
      "Iron and manganese",
      "Suspended materials (colloidal substances)"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_38",
    "source": "dsa2",
    "type": "best_answer",
    "number": 38,
    "question": "What is the important difference between MCL and MCLG?",
    "answer": 2,
    "options": [
      "MCLG is always established before the MCL",
      "MCLG is nonenforceable and MCL is an enforceable standard",
      "MCLG is preferred by regulatory agencies in lieu of the MCL",
      "MCL is always lower than the MCLG"
    ],
    "tags": []
  },
  {
    "id": "dsa2_best_answer_39",
    "source": "dsa2",
    "type": "best_answer",
    "number": 39,
    "question": "What causes backflow situations in distribution systems?",
    "answer": 2,
    "options": [
      "Defective clearwell safety valves",
      "Either back pressure or back siphonage",
      "Failure of the filter backwash system",
      "Malfunctioning distribution system sampling stations"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_2",
    "source": "dsa2",
    "type": "select_all",
    "number": 2,
    "question": "What can be added to increase the pH of water being treated with a continuous regeneration (CR) manganese green sand plant?",
    "answer": [
      2,
      4
    ],
    "options": [
      "Muriatic acid",
      "Sodium carbonate",
      "Sodium chloride",
      "Sodium hydroxide",
      "Sulfuric acid"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_3",
    "source": "dsa2",
    "type": "select_all",
    "number": 3,
    "question": "How can an operator minimize red water or dirty water problems and complaints?",
    "answer": [
      1,
      2,
      4,
      5
    ],
    "options": [
      "Deliver stable (noncorrosive) water to the distribution system",
      "Ensure the water pumped into the distribution system contains a little to no iron and manganese",
      "Keep the health department informed of the water quality conditions",
      "Maintain a free chlorine residual in all water throughout the distribution system",
      "Provide adequate treatment to control iron and manganese"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_17",
    "source": "dsa2",
    "type": "select_all",
    "number": 17,
    "question": "Which commonly used chemicals require special handling in reverse osmosis plant operation?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Acids",
      "Chlorine",
      "Citric acid",
      "Formaldehyde",
      "Sodium hexametaphosphate"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_28",
    "source": "dsa2",
    "type": "select_all",
    "number": 28,
    "question": "Which items can cause electronic instrument problems?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Excessive heat",
      "Static electricity",
      "Temporary power failures",
      "Tripped panel circuit breakers",
      "Voltage surges; lightning"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_33",
    "source": "dsa2",
    "type": "select_all",
    "number": 33,
    "question": "Which steps or tasks are recommended before entry into a confined space?",
    "answer": [
      1,
      2,
      3,
      4,
      5
    ],
    "options": [
      "Empty, flush, or purge the space of any harmful substances",
      "Identify and isolate any lines that contain harmful substances to the work area",
      "If an atmosphere hazard is possible use portable blowers to further ventilate the area",
      "Monitor the atmosphere to determine if dangerous air contamination and/ or oxygen deficiency exists",
      "Record the atmospheric test results and keep them at the site throughout the work period"
    ],
    "tags": []
  },
  {
    "id": "dsa2_select_all_34",
    "source": "dsa2",
    "type": "select_all",
    "number": 34,
    "question": "Which steps must be completed in order to prepare a spectrophotometer calibration curve?",
    "answer": [
      2,
      4,
      5
    ],
    "options": [
      "Develop a laboratory bench sheet for recording the test results",
      "Prepare a series of standards",
      "Read the spectrophotometer manufacturer's operation manual",
      "Treat the standard solution and a blank with the colour developing reagent",
      "Use the spectrophotometer to determine the absorbance or transmittance at the specified wavelength"
    ],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_1",
    "source": "dsa2",
    "type": "flashcard",
    "number": 1,
    "question": "Why should iron and manganese be controlled in drinking water?",
    "answer": "Clothes washed may become stained, and Fe+Mn promote iron bacteria that form slime in distribution mains. The slime—rust-colored from iron and black from manganese—can slough off during flow changes, causing dirty water along with unpleasant tastes and odors.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_3",
    "source": "dsa2",
    "type": "flashcard",
    "number": 3,
    "question": "How does an operator decide when to backwash a manganese green sand filter?",
    "answer": "Typically when head loss reaches 10PSI or after treating a predetermined number of gallons of water.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_4",
    "source": "dsa2",
    "type": "flashcard",
    "number": 4,
    "question": "Why are drinking waters fluoridated?",
    "answer": "To reduce the frequency of dental cavities in children.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_5",
    "source": "dsa2",
    "type": "flashcard",
    "number": 5,
    "question": "How can water be softened prior to use with fluoridation equipment?",
    "answer": "By the use of zeolite ion exchangers",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_7",
    "source": "dsa2",
    "type": "flashcard",
    "number": 7,
    "question": "Why should water be softened?",
    "answer": "Hard waters cause difficulties in doing the laundry and dishwashing in the household. Scale coats the inside of water heaters and can negatively effect industrial processes.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsa2_flashcard_9",
    "source": "dsa2",
    "type": "flashcard",
    "number": 9,
    "question": "Why is sludge sometimes recirculated back to the primary mix area of conventional plants?",
    "answer": "To help seed the process, recirculation speeds up the precipitation process and may reduce some chemical requirements.",
    "options": [],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_1",
    "source": "dsb1",
    "type": "factsheet",
    "number": 1,
    "question": "Enteric protozoa: Giardia and Cryptosporidium",
    "answer": "Minimum 3 log removal/ inactivation of cysts/ oocysts",
    "options": [
      "Sources human & animal feces",
      "Gastrointestinal upset - nausea, vomiting, diarrhoea"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_2",
    "source": "dsb1",
    "type": "factsheet",
    "number": 2,
    "question": "Enteric viruses",
    "answer": "Minimum 4 log removal/ inactivation",
    "options": [
      "Sources human feces",
      "Gastrointestinal upset - nausea, vomiting, diarrhoea",
      "Less common; respiratory, central nervous system, liver, muscular issues",
      "Detected in both surface and ground water sources",
      "Disinfection is a critical barrier"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_3",
    "source": "dsb1",
    "type": "factsheet",
    "number": 3,
    "question": "Escherichia coli | E. coli",
    "answer": "MAC: None/ 100 mL",
    "options": [
      "Sources human & animal feces",
      "Fecal contamination indicator",
      "Pathogens in human and\r\nanimal feces pose the\r\ngreatest immediate danger\r\nto public health"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_4",
    "source": "dsb1",
    "type": "factsheet",
    "number": 4,
    "question": "Total coliforms",
    "answer": "MAC: None/ 100 mL",
    "options": [
      "Sources human & animal feces, naturally occuring in soils",
      "Not used as indicators for pathogenic microorganisms - used to determine how the system is operating",
      "Indicate changes in water quality in distribution system"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_5",
    "source": "dsb1",
    "type": "factsheet",
    "number": 5,
    "question": "Turbidity",
    "answer": "Conventional/ Direct Filtration <= 0.3 NTU in 95% of measurements per filter/ month - never exceed 1.0 NTU",
    "options": [
      "Slow Sand/ Diatomaceous Earth <= 1.0 NTU in 95% of measurements per filter/ month - never exceed 3.0 NTU",
      "Membrane Filtration <= 0.1 NTU in 99% of measurements per filter/ month - measurements above 0.1 NTU for 15 minutes should trigger immediate investigation",
      "Inorganic: clays, silts, metal precipitates",
      "Organic: decomposed plant/ animal debris, microorganisms",
      "Particles can hide microorganisms from disinfection, trap heavy metals, etc"
    ],
    "tags": []
  },
  {
    "id": "dsb1_factsheet_6",
    "source": "dsb1",
    "type": "factsheet",
    "number": 6,
    "question": "Aluminum",
    "answer": "MAC: 2.9 mg/L",
    "options": [
      "OG: 0.1 mg/L",
      "Natural, coagulant aluminum salts",
      "Neuromuscular effects"
    ],
    "tags": []
  }
];

// For Node.js / module usage
if (typeof module !== "undefined") module.exports = { questions };
